class Album {
    constructor(uri, name, artist) {
        new RandomObject("album", name, artist, "", "https://open.spotify.com/embed/album/" + uri, "spotify:album:" + uri + ":play");
    }
}

new Album("09mWpzpUOSjjvK2iNqEIYn", "Communion (Deluxe)", "Years & Years");
new Album("1OUGPngAngAxjliRlrAc6v", "Palo Santo (Deluxe)", "Years & Years");
new Album("7eyQXxuf2nGj9d2367Gi5f", "In Rainbows", "Radiohead");
new Album("4Q6CHV4X8HsF80bVxHQkc6", "La Otra Dimensión", "El Mató a un Policía Motorizado");
new Album("4mSRBCoYBRglpUkODqm7Jh", "El Nuevo Magnetismo (2003 - 2011)", "El Mató a un Policía Motorizado");
new Album("355bjCHzRJztCzaG5Za4gq", "El Mal Querer", "ROSALÍA");
new Album("4nCH12hucZpiPxsCm06ayC", "Texturas", "CLUBZ");
new Album("1yyCXBEu27Ia1Y3torWIwC", "American Boyfriend: A Suburban Love Story", "Kevin Abstract");
new Album("6wi40lIjhukePWyXRKY7qO", "ARIZONA BABY", "Kevin Abstract");
new Album("3ecRdDscGaPIeYhj3l3IDV", "Fatigue", "Zach Farache");
new Album("3vL4mBi9RLDYnmzfXCC7sw", "No Somos Los Mismos de Ayer (EP)", "NORTE");
new Album("1roJDKHlQXToKPS4l9JI8H", "Todo Sentimiento Es Ya Memoria", "NORTE");
new Album("0P2kTQ7mJ3z7CFjII7GWkw", "Spring EP", "Wallows");
new Album("7nVdkG4gZZxB1I1RLN27fJ", "Macadelic (Remastered Edition)", "Mac Miller");
new Album("10UscF31tC7Sz8S2a1mGbM", "Bucket List Project", "Saba");
new Album("4yP0hdKOZPNshxUOjY0cZj", "After Hours", "The Weeknd");
new Album("6yoGOJsTjU7w2amKcUUX7S", "Blood", "Rhye");
new Album("32KdoFFhgjCLdU0DWL71tx", "Camp", "Childish Gambino");
new Album("4MkY7K5eyXl0Ts42KLCyir", "Eclipse", "Twin Shadow");
new Album("5eIgu8uJ3H18h8vVqJYggZ", "Caer", "Twin Shadow");
new Album("1PgfRdl3lPyACfUGH4pquG", "22, A Million", "Bon Iver");
new Album("1JlvIsP2f6ckoa62aN7kLn", "Bon Iver", "Bon Iver");
new Album("54DU59anGQsdrFP7utpshG", "i,i", "Bon Iver");
new Album("15TFB6uLZlb3gnCysRrLix", "Superorganism", "Superorganism");
new Album("6FqMq0fTs08MG0vf2P7qNx", "Ylang Ylang EP", "FKJ");
new Album("0jJ7mMkCkTe7p9EJgSRxgi", "French Kiwi Juice", "FKJ");
new Album("66aYL3AZPfk6leHxlJDYQ0", "Deceiver", "DIIV");
new Album("5PPPABn2aZ0jRuHPMONwSR", "Is the Is Are", "DIIV");
new Album("4nSWX5A4xVomzrOEGDKLQ6", "Slowdive", "Slowdive");
new Album("6KC06etxRkjUDzvfxU5sgA", "Homey", "Chon");
new Album("31xSTnqna5WeOdCN0AJMNJ", "Chon", "Chon");
new Album("612LP8ZkujVEbvAfD8huGz", "Infest The Rats' Nest", "King Gizzard & The Lizard Wizard");
new Album("0nmCwOAFeqD69X1MWwKTS6", "It Was Divine", "Alina Baraz");
new Album("4EPQtdq6vvwxuYeQTrwDVY", "Isolation", "Kali Uchis");
new Album("480YjUeLRvXFcbS2HeXfuU", "You", "Larry Lovestein & The Velvet Revival");
new Album("22cFcAQkydpTzeSKQZEKv0", "Supermodel", "Foster The People");
new Album("7hf4Do8ywyKVJiwQqIexc2", "Autoterapia", "IZAL");
new Album("4WI3oFEsDiHU3I5xHz88sF", "I Forget Where We Were", "Ben Howard");
new Album("4L9qXAXmnMEIvnvG8xon3F", "James Blake", "James Blake");
new Album("0qYRbCu2dmz948wOiROlcC", "Godspeed", "James Blake");
new Album("3U2omtdhP8u72J2afr5UQG", "Subluxe", "Healy");
new Album("3T6hM5LbfFxp9AUjnJP6fN", "Natural Affair", "The Growlers");
new Album("4M77jtvYBaemmK9IqbVJzr", "Never Nothing", "Super Whatevr");
new Album("1VNif3AzZqvHC4xXGnvX4g", "So Long And Thanks", "Milmine");
new Album("33szFJNdxgVGQa518rOohL", "La Dinastía Scorpio", "El Mató a un Policía Motorizado");
new Album("0FZK97MXMm5mUQ8mtudjuK", "The Black Parade", "My Chemical Romance");
new Album("6nVACH6a27eOWiumAJhDWS", "Modal Soul", "Nujabes");
new Album("2G4bYCAO1h9mQvFUYbXzuh", "La Viuda", "The Guadaloops");
new Album("6Sts4Yh7KsDFwq2yTWrGGV", "The Black Saint And The Sinner Lady", "Charles Mingus");
new Album("2A4sin52eEjkavgFwPdEoZ", "Sound & Color", "Alabama Shakes");
new Album("1BiLtcjrB3K5nJOaJ8gmaD", "Exitos Con Trio", "Javier Solís");
new Album("2t1JMhasqIbvoWb89rt2AV", "Lucio Dalla (Legacy Edition)", "Lucio Dalla");
new Album("14xxjLlbGy8ACm4MorBjD5", "Lost In The Dream", "The War On Drugs");
new Album("4IFpj2jyRcugt1yzH82m3E", "SYRE", "Jaden");
new Album("7MtrCHFK57syVaitrSwSAY", "Silver Rose", "Silver Rose");
new Album("6zmDdgPRKrvYwXk8eWv3iK", "6 Feet Beneath The Moon", "King Krule");
new Album("6UsJMFZbhzvWrTDX7vr3pr", "Almanueva", "The Guadaloops");
new Album("6Ulu31dfRTpIAud08ZIhXd", "The OOZ", "King Krule");
new Album("7uwHUvVHDAEKxyXCoZYFIF", "Florence (Original Soundtrack)", "Kevin Penkin");
new Album("5yOO5ZvqDZx5Sr8jOGtWRR", "Eternal Sunshine Of The Spotless Mind", "Various Artists");
new Album("0LIWkw76T7O499slpRTeQ1", "Lady Bird (Original Motion Picture Soundtrack)", "Jon Brion");
new Album("3g5x7FHBksAsL5syfukMwI", "Chronovision", "Oberhofer");
new Album("0MlfbX8SY5emphjwETJSRu", "D'arcy", "No Somos Marineros");
new Album("1tuoWW0TpoI5oacIjwYBdL", "Making a Door Less Open", "Car Seat Headrest");
new Album("0kAlEeID2MPd2JYT3Iwegp", "Delaware", "Drop Nineteens");
new Album("409ucdW5uJn96fKCsHWPDg", "My Mind Makes Noises", "Pale Waves");
new Album("1AVZ6ej2XcpHtlTqTy91qt", "Tiempos Raros", "El Shirota");
new Album("1tFsLlrFZVNpExRX3cg0WV", "Smells Like Quarantine Spirit (Live Session)", "Sunshine Pink");
new Album("162WY2ZAoenA3bCPZ0fXJH", "Dwell", "The Moving Pictures");
new Album("0WzOtZBpXvWdNdH7hCJ4qo", "K.I.D.S.", "Mac Miller");
new Album("2qGq0iQFEjrcDprsd7QSFx", "They Want My Soul", "Spoon");
new Album("31WBtpvBAN0heOz3YUuVnI", "The Silhouette", "Cold Violets");
new Album("2NBVxjZcbH5H1N1Ab2ExDH", "Apricot Princess", "Rex Orange County");
new Album("600ClrWRsAr7jZ0qjaBLHz", "3.15.20", "Childish Gambino");
new Album("27ThgFMUAx3MXLQ297DzWF", "Hive Mind", "The Internet");
new Album("2O7cV8FLOPbOttvFVCU1bR", "Mariposa", "Felly");
new Album("4alcGHjstaALJHHiljfy3H", "DAMN. COLLECTORS EDITION.", "Kendrick Lamar");
new Album("51WLEfPEEkzAWurvuY6Gco", "Veteran", "JPEGMAFIA");
new Album("5LsyqeWryTmxsmda4xkm5a", "UNLOCKED", "Denzel Curry");
new Album("2epVE7UZnRSaCIJb0mjIPM", "Blue Scholars", "Blue Scholars");
new Album("7JbbUP152jaRbhQ7CJ1DOy", "Musas (Un Homenaje al Folclore Latinoamericano en Manos de Los Macorinos), Vol. 2", "Natalia Lafourcade");
new Album("4hBTxv4QRPePXCFcEI7Vjp", "blink-182", "blink-182");
new Album("2yAyZp16EbanQ9pBwQs70x", "A Different Age", "Current Joys");
new Album("3wUv2IjD5hPrqlPakpczQa", "I Don't Like Shit, I Don't Go Outside: An Album by Earl Sweatshirt", "Earl Sweatshirt");
new Album("5cW1jp3GGSe06JfZGPziW8", "Two Songs", "Art Contest");
new Album("30isRfL4u7fowKgTVsydDt", "Musas (Un Homenaje al Folclore Latinoamericano en Manos de Los Macorinos, Vol. 1)", "Natalia Lafourcade");
new Album("748dZDqSZy6aPXKcI9H80u", "good kid, m.A.A.d city (Deluxe)", "Kendrick Lamar");
new Album("1ywMOLYln5Df2bF70jtydj", "Disco de Oro", "Little Jesus");
new Album("2Tyx5dLhHYkx6zeAdVaTzN", "GO:OD AM", "Mac Miller");
new Album("76cek8jEdNsxH60aUu8Qtj", "To Pimp A Butterfly", "Kendrick Lamar");
new Album("6Te111t5gDZ7W94myHRqUt", "CARE FOR ME", "Saba");
new Album("1uoN9djowbSSttHLe2Nfwn", "Toothpick", "Kai Straw");
new Album("4TkmrrpjlPoCPpGyDN3rkF", "A Deeper Understanding", "The War On Drugs");
new Album("33ZqJmmqFE8Z7Ak1Lxbnfb", "The 1975", "The 1975");
new Album("2iA7rzpQsOfAPkfH4Ekp7f", "Ordinary Corrupt Human Love", "Deafheaven");
new Album("7MLDnEVUacleMDICnnAWuF", "Man Alive!", "King Krule");
new Album("5ilsl5R2lGACTnPZMKIp7o", "All My Heroes Are Cornballs", "JPEGMAFIA");
new Album("5YCFp2g2ZZUc0bKNAWyYHN", "La Sintesis O'Konor", "El Mató a un Policía Motorizado");
new Album("2X4swA3UkpqAS8bbXYgP9k", "Destellos", "CLUBZ");
new Album("5u8hliZZtH3mc6o7BJRmVP", "Dead Cities, Red Seas & Lost Ghosts", "M83");
new Album("7JX33G6W9Zi9ViEvUumX8E", "Norte (Japanese Version)", "Little Jesus");
new Album("1ny9ec75rSo3SOg1EiDRRW", "Panoramas", "Klaatu Suuns");
new Album("2kKXGWaCEl06EKZ4DxBJIT", "Sunbather", "Deafheaven");
new Album("6V9YnBmFjWmXCBaUVRCVXP", "Amnesiac", "Radiohead");
new Album("6PWXKiakqhI17mTYM4y6oY", "A Brief Inquiry Into Online Relationships", "The 1975");
new Album("26DseQO366JfXwIP7dIgQj", "Teens of Denial", "Car Seat Headrest");
new Album("2xkZV2Hl1Omi8rk2D7t5lN", "The New Abnormal", "The Strokes");
new Album("6yDcHjoEqNkkl9UC6KSlFE", "Un Canto por México, Vol. 1", "Natalia Lafourcade");
new Album("1TobaDcf1kuip5YpaM8crC", "7", "7");
new Album("7fFUZ9J5aTu18MYcBiPOny", "Go Slow", "deca joins");
new Album("5ooYAFLqUJiXfGzjVgG5N0", "Río Salvaje", "Little Jesus");
new Album("101nIHm9fdR1wLMgjiLmhT", "Illiterate Light", "Illiterate Light");
new Album("4Carzsnpd6yvuHZ49I0oz8", "'Awaken, My Love!'", "Childish Gambino");
new Album("7xV2TzoaVc0ycW7fwBwAml", "Fine Line", "Harry Styles");
new Album("3wRBlpk5PRoixwOnLujTal", "American Football", "American Football");
new Album("3PRMdCzUdj3LmnyLVU1cLr", "Friendship", "Big Big Love");
new Album("3XIKKZu6j73mu2MKFdi9JX", "María", "Cazamos Cometas");
new Album("1rBDUTycaO0IFrCGlz3l32", "Beacon", "Matt Duncan");
new Album("5zi7WsKlIiUXv09tbGLKsE", "IGOR", "Tyler, The Creator");
new Album("1JFmNyVPdBF1ECvv4fhpW4", "I like it when you sleep, for you are so beautiful yet so unaware of it", "The 1975");
new Album("3T02fCxAjApu18taJLLbyN", "Watching Movies with the Sound Off (Deluxe Edition)", "Mac Miller");
new Album("6f6tko6NWoH00cyFOl4VYQ", "The Divine Feminine", "Mac Miller");
new Album("5wtE5aLX5r7jOosmPhJhhk", "Swimming", "Mac Miller");
new Album("1YZ3k65Mqw3G8FzYlW1mmp", "Circles (Deluxe)", "Mac Miller");
new Album("6EB14IXV5oyOiItGBv7mtG", "Hurry up, We're Dreaming", "M83");
new Album("7viNUmZZ8ztn2UB4XB3jIL", "2014 Forest Hills Drive", "J. Cole");
new Album("3CCnGldVQ90c26aFATC1PW", "4 Your Eyez Only", "J. Cole");
new Album("3mH6qwIy9crq0I9YQbOuDf", "Blonde", "Frank Ocean");
new Album("4GNIhgEGXzWGAefgN5qjdU", "Because the Internet", "Childish Gambino");
new Album("20U1UWeGcGq7JVW0tf8yfH", "Twin Fantasy", "Car Seat Headrest");
