class Movie {
    constructor(name) {
        new RandomObject("movie", name, "", "", "./search/?q=" + name.replace(' ', '+').replace("'", '%27').replace(":", '%3A') + "+movie");
    }
}

new Movie("10 Things I Hate About You");
new Movie("50 First Dates");
new Movie("500 Days of Summer");
new Movie("Akira");
new Movie("Amar");
new Movie("Amerian History X");
new Movie("American Beauty");
new Movie("Amores Perros");
new Movie("Annihilation");
new Movie("Anomalisa");
new Movie("Arrival");
new Movie("August Rush");
new Movie("Big Fish");
new Movie("Blade Runner");
new Movie("Blade Runner 2049");
new Movie("Blue Valentine");
new Movie("Catch Me If You Can");
new Movie("Children of Men");
new Movie("Cloverfield");
new Movie("Dead Poets Society");
new Movie("Drive");
new Movie("El Club de los Insomnes");
new Movie("El Dorado");
new Movie("El Señor de los Anillos");
new Movie("Ender's Game");
new Movie("Eternal Sunshine of the Spotless Mind");
new Movie("Ex-Machina");
new Movie("Fantastic Mr.Fox");
new Movie("Forrest Gump");
new Movie("Full Metal Jacket");
new Movie("Gone Girl");
new Movie("Green Book");
new Movie("Green Street Hooligans");
new Movie("Güeros");
new Movie("Her");
new Movie("I Lost My Body");
new Movie("Interstellar");
new Movie("Into The Spiderverse");
new Movie("Into The Wild");
new Movie("Isle of Dogs");
new Movie("Johny English");
new Movie("Kill Bill Vol:1");
new Movie("Kubo And The Two Strings");
new Movie("La Deglada Línea Amarilla");
new Movie("La la land");
new Movie("La Vida Inmoral de la Pareja Ideal");
new Movie("Las Locuras del Emperador");
new Movie("Les Misérables");
new Movie("Life Aquatic with Steve Zissou");
new Movie("Logan");
new Movie("Looper");
new Movie("Mad Max: Fury Road");
new Movie("Manchester By The Sea");
new Movie("Marriage Story");
new Movie("Megamind");
new Movie("Melody");
new Movie("Memento");
new Movie("Monty Python and the Holy Grail");
new Movie("Monty Python's Life of Brian");
new Movie("Moonlight");
new Movie("Moonrise Kingdom");
new Movie("Newness");
new Movie("Pacific Rim");
new Movie("Parasite");
new Movie("Porco Rosso");
new Movie("Pride And Prejudice");
new Movie("Raw");
new Movie("Remember The Titans");
new Movie("Robot & Frank");
new Movie("Rushmore");
new Movie("Scooby Doo! La Película");
new Movie("Scott Pilgrim vs The World");
new Movie("Shrek 2");
new Movie("Sicario");
new Movie("Sing Street");
new Movie("Someone Great");
new Movie("Somewhere In Time");
new Movie("Spirit");
new Movie("Swiss Army Man");
new Movie("Tarzan");
new Movie("The Beaver");
new Movie("The Breakfast Club");
new Movie("The Graduate");
new Movie("The Invisible Guest");
new Movie("The Lobster");
new Movie("The Meyerowitz Stories");
new Movie("The Perks of Being a Wallflower");
new Movie("The Skin I Live In");
new Movie("The Truman Show");
new Movie("The Warriors");
new Movie("Uncut Gems");
new Movie("What Dreams May Come");
new Movie("What We Do In The Shadows");
new Movie("Ya No Estoy Aquí");
new Movie("Your name");
new Movie("Lady Bird");
new Movie("Spirited Away");
new Movie("Lost in Translation");
new Movie("The Notebook");
new Movie("Your name");
new Movie("The SpongeBob SquarePantsMovie");
new Movie("Requiem for a Dream");
new Movie("Your name");
