class Song {
    constructor(uri, name, artist) {
        new RandomObject("song", name, artist, "", "https://open.spotify.com/embed/track/" + uri, "spotify:track:" + uri + ":play");
    }
}

new Song("0Tz7GngseHZANJOkCSEksX", "romA (LRDP Maqueta)", "Sabino");
new Song("16umSNZfofRpDqTvf8DIAo", "Wings", "Mac Miller");
new Song("2oHDXaIgFkD41mkocZKMKC", "Rocketman (feat. Atlas & Lando!)", "AL-X The Great");
new Song("6dFn6my1sHK2bcf23GlHwM", "2009", "Mac Miller");
new Song("5gPXLYNb9XRFHgRfcUKiHA", "Cine Permanencia Voluntaria", "Little Jesus");
new Song("2jZgzSxNSg1hTCq0ewWHGJ", "Junk Of The Heart (Happy)", "The Kooks");
new Song("6FevCNAtHbDt3YO2gMYVxE", "Nuevos Amigos", "Little Jesus");
new Song("5LpxWYdZuWHWxOwlrQslO1", "Eyes Shut", "Years & Years");
new Song("01z2fBGB8Hl3Jd3zXe4IXR", "Come Back to Earth", "Mac Miller");
new Song("5VqCEVBScatH05aM7KbABm", "Juvenescence", "Verzache");
new Song("7BVwi9cIzSc6tpyxsp47vJ", "Mess Is Mine", "Vance Joy");
new Song("75GwJi8ruSsNTBLoGBMFBm", "drift/(:(", "Alek Olsen");
new Song("54XGKvGZwA7xB3Uu5vef0C", "The Ballad Of Me And My Brain", "The 1975");
new Song("4LX270g9HEBkA0qYtGAel8", "Los Bajos Fondos", "No Somos Marineros");
new Song("35r28RDot7nPE7y9K9H7l0", "Feeling Whitney", "Post Malone");
new Song("2L9mXwt6vJ3FxVxf7jsGkd", "$150 / roll widdit", "Healy");
new Song("4XOlo2K3XX1ICy1KfEiWyO", "Solo", "Samsa");
new Song("5Pm3e0YoHBJSPDUI7FC2jh", "Halls", "Andrew McMahon in the Wilderness");
new Song("2jdw2tc29bqJwToyGvKgJm", "Ninety", "Jaden");
new Song("0pYtGkBAQdmZhPjzd6DLJ9", "The Fort", "Zack Villere");
new Song("2ZltjIqztEpZtafc8w0I9t", "3005", "Childish Gambino");
new Song("1MSM3Fo2fvnwVqMcz8Jhjq", "Cecilia And The Satellite", "Andrew McMahon in the Wilderness");
new Song("5nWbbQ0sIEabqPxAdqmh66", "Sweet Disposition", "The Temper Trap");
new Song("0u256fkohocCZSCJ8J79TX", "Hiccup", "Verzache");
new Song("7gYwIAHB6VxzLJFSZMMv8i", "I Forget Where We Were", "Ben Howard");
new Song("7yq4Qj7cqayVTp3FF9CWbm", "Riptide", "Vance Joy");
new Song("1Qawn8hSErf3X5idQ2LEzD", "Baby", "Born Without Bones");
new Song("5hNn942bPHLglOV8fmw2dh", "SYRE", "Jaden");
new Song("6kVku2CoE7fbD29miiutzw", "Butterflies", "Samsa");
new Song("39NDBdU5Xkm5pCFGa5kZtI", "Ladders", "Mac Miller");
new Song("4GjRDgb77p27GQnbZpv1OJ", "Me", "The 1975");
new Song("4bjCLt9DmQ7nlcw1TUDh7U", "Fuego", "El Mató a un Policía Motorizado");
new Song("1ZwJALwnYbeHdEVCNVmniz", "You", "The 1975");
new Song("5HXzRgF4UmRdYR3B2I0unh", "stay", "Lewis Watson");
new Song("3UEpvJxIpzbR3w0oOa0zbB", "Intro", "Cazamos Cometas");
new Song("1XczdQt6RKNkEQfPqUsi3q", "All I Want", "Kodaline");
new Song("6VuUMo1TusnqBxLTnr3hOI", "Brillas", "León Larregui");
new Song("0QB71BDzh36guAExsTIgNO", "Only Love", "Ben Howard");
new Song("3aVyHFxRkf8lSjhWdJ68AW", "Just Another Girl", "The Killers");
new Song("5mEyCUtI36Jmu2KNQQ4jaw", "Girls Like You", "The Naked And Famous");
new Song("0RKsqN4n1xViUoeAoQdKg2", "Burnt Offering", "Blue Scholars");
new Song("5iUQMwxUPdJBFeGkePtM66", "Dang! (feat. Anderson .Paak)", "Mac Miller");
new Song("1olz3HctPa2yXmSniaCNLN", "Waiting for You", "Verzache");
new Song("7l5j3FapCyr6HxUgoAynM2", "Gap in the Clouds", "Yellow Days");
new Song("0wIFAHbaUucA8mog7Y2IDD", "Sex", "The 1975");
new Song("5mxcbJ45LLpNZIJlFziPZ4", "Komodo", "Samsa");
new Song("5wuwqS7kCVhmQ82JFm6KhZ", "Charlie Brown", "Zach Farache");
new Song("0QRF1OiXaGh01fIrgyLhLM", "Be Yourself", "Ben's Brother");
new Song("2dgrYdgguVZKeCsrVb9XEs", "What's the Use?", "Mac Miller");
new Song("2LpcEVDlL4j6SDQqpKzopv", "Ven a Mí (feat. Caloncho)", "Leonel García");
new Song("6pwh8jxrpOoXAXhjAhIvFE", "Czech One", "King Krule");
new Song("7dXyQvTkoiNVtsXAgFTXmL", "Bermondsey Bosom (Right)", "King Krule");
new Song("2LpcTDgPrMexPloLcHsSWl", "A Slide In (New Drugs)", "King Krule");
new Song("1wpin6CIQlmEUuZvALQSVw", "Aquarium", "Mac Miller");
new Song("3EjxAbEOH28icEK1ZFOUSh", "Essa Tal Liberdade", "Só Pra Contrariar");
new Song("1gTFwhHHsk4LwKGcLLe7r5", "Dmi Thing in Which New Information Is Introduced", "Jon Brion");
new Song("67vV72Oo7aty9EqYj1mwlR", "Perfecto Miserable", "King Krule");
new Song("4Hd4pcfUFQ5Czju0atfAKg", "Bermondsey Bosom (Left)", "King Krule");
new Song("2ELAmhHemyQG2U9TwLuusd", "The Ooz", "King Krule");
new Song("3kaDHM8oyxYevx5BITFFic", "Midnight 01 (Deep Sea Diver)", "King Krule");
new Song("194bcmwinAQqnkzdMRqju0", "La Lune", "King Krule");
new Song("1QMT8kb4hx6MZKIhUBoEtz", "The Cadet Leaps", "King Krule");
new Song("0GqkFzrmgujTMyGd01nCR5", "Biscuit Town", "King Krule");
new Song("3M8FzayQWtkvOhqMn2V4T2", "Lean on Me", "Bill Withers");
new Song("5v9GvZIJuD7QAkGIO8CHpm", "Vidual", "King Krule");
new Song("0PgU3qcRXrOKHkA1BMJNSj", "Half Man Half Shark", "King Krule");
new Song("3sa4mkNrXnhIsqDMuHx8ZX", "Besar en Luna Llena", "The Guadaloops");
new Song("38TrmGyKtQ4r9JxEfk8xlT", "Emergency Blimp", "King Krule");
new Song("0xE4LEFzSNGsz1F6kvXsHU", "Circles", "Mac Miller");
new Song("1jhtxc7ON8ZzgvWGPwWXUN", "Baby Blue", "King Krule");
new Song("35rf8iduzQ7vd8hFbDlv0o", "Easy Easy", "King Krule");
new Song("37UNeKSzilH978feP03T04", "Reconcile", "Jon Brion");
new Song("3z3BsIVe0RHu7m6J1KZxg1", "My Boy (Twin Fantasy)", "Car Seat Headrest");
new Song("57t8BTQgH5qfHQXosfZ2pk", "Exploration", "Kevin Penkin");
new Song("5jSBnH9NyaNP5zdSB3pwgu", "Gimme Love", "Joji");
new Song("67u55G1oKniIsCBQoM43h1", "Spaghetti", "City of the Sun");
new Song("7b0NutXQ71gr9A8661Qc6d", "Groceries", "Kevin Penkin");
new Song("23hTcFAu2WU0uEizMNe5kz", "Almanueva", "The Guadaloops");
new Song("3bBbpnAT7JG0v2B2IkUppV", "Niña Surf", "Los Blenders");
new Song("4Vkk3ZL9KHsiN4o7psSaRo", "Cadet Limbo", "King Krule");
new Song("1AsQFm7ORbr4NEZ0dUltOY", "Way It Goes", "Hippo Campus");
new Song("1fkB6ypnGbxahR3bGij8xU", "And When I Die", "Mark Winkler");
new Song("3sv9x84kPhVfHh1qpwa0Ks", "7/4 Shoreline", "Broken Social Scene");
new Song("6D43oUO6nImERk2psfXdNY", "Afterlife", "Arcade Fire");
new Song("6yzzno5cXBkh5c6UzRxcyM", "Lady Bird", "Jon Brion");
new Song("1Eu8k38S6dFMuool5amlmR", "Wada Na Tod - From 'Dil Tujhko Diya'", "Lata Mangeshkar");
new Song("63fj7dR4QGRHDHKZStUuAY", "Bad Things", "Milky Chance");
new Song("034shJt5wcKAgzjfQTu8Ys", "Strings That Tie To You - From 'Eternal Sunshine of the Spotless Mind'/Soundtrack Version", "Jon Brion");
new Song("0IHWITC8b1u4edMKWZaJ2K", "Sueños de Amor", "Silver Rose");
new Song("19YKaevk2bce4odJkP5L22", "Nikes", "Frank Ocean");
new Song("2sel6x4NGeSVLr7TMk7oQT", "Logos", "King Krule");
new Song("4MxT3iMbBOCFbvJMfRD4Ox", "Now?", "Sunshine Pink");
new Song("51R5mPcJjOnfv9lKY1u5sW", "Never Meant", "American Football");
new Song("5mWhSQfWEeBZD9YTd4yyFc", "Dum Surfer", "King Krule");
new Song("6HJpRs15t69hbKxIhlWwgC", "TBC", "Ragazzi");
new Song("6N5DRCQUSXT1qQqmqsO92B", "Party All the Time", "Eddie Murphy");
new Song("4M9gZEtOSf2I1hyGNvZbpF", "Take Me Home", "Silver Rose");
new Song("77gQSJlncgT3HWmBfy9CQ9", "Aire", "Nicole Horts");
new Song("5oUKoRSLP1GoAccvH4wXXj", "Cellular", "King Krule");
new Song("0kc4G5tEdtmTB0w3gYmb01", "Desencuentro (feat. Soko)", "Residente");
new Song("0gqsJm7b3KPSpqA2FsVn53", "Danny Nedelko", "IDLES");
new Song("1HyImWEaQ6ApypgRa7oBMX", "Sea of Dreams", "Oberhofer");
new Song("2LMkwUfqC6S6s6qDVlEuzV", "White Ferrari", "Frank Ocean");
new Song("1IF5UcqRO42D12vYwceOY6", "From the Dining Table", "Harry Styles");
new Song("1THOENDCBvX13qNkwctXlW", "Ghosts", "Mayday Parade");
new Song("4HbeGjbt7u3pvwDk1vN7P0", "Mystery of Love", "Sufjan Stevens");
new Song("5WfACgyEk4rwdWU3rrzNt1", "Godspeed", "James Blake");
new Song("6IBpFG2LU2udYofIuROp3w", "Lost In The Light", "Bahamas");
new Song("6QgPfp0ARMLlie81jVfsUb", "Give Me My Month", "James Blake");
new Song("3Gda1sTo2ZjbztjjsnAsP3", "Slip Away", "Perfume Genius");
new Song("3VwZqgfrM3xb1usuLprkTu", "cellophane", "FKA twigs");
new Song("6QbI1KSaDQhftv6aGHT5vn", "Bodys", "Car Seat Headrest");
new Song("2IbQBVzWkT4CF9aEUWek2o", "The Wave", "Colouring");
new Song("7doSYW71rxRVAj49ilysHd", "Our Love Remains", "rei brown");
new Song("0RDly6TkvnlYu26RuBw0Ym", "Soy vírgen y soy leal", "Julieta Venegas");
new Song("2lV8YY0GQYXgtUWXM4NJ4X", "4:00A.M.", "Taeko Onuki");
new Song("0HMjXBAZmSYOTTi33WpMso", "History", "One Direction");
new Song("5lMJTWXtWXFqKpi1a0qna9", "A Word of Wisdom", "M83");
new Song("1Bv3h7Vc4AaYA2BcSM3rVd", "All I Wanted", "Paramore");
new Song("4lD7gHKF1e8Y9stQuVezZB", "ghostin", "Ariana Grande");
new Song("5HMlQNbqL0TuIl8fGjBmYG", "Rottweiler", "IDLES");
new Song("10qaFO9To9Dkn8Qgw3B115", "No Te Importa Que Me Duela", "Lara Project");
new Song("18CK4TdFJhPYQtUX2fq8D8", "Reanimator (feat. Yves Tumor)", "Joji");
new Song("2hfoyc7ve6xM4ZEiNIiU1B", "Gimme Love", "Joji");
new Song("34xTFwjPQ1dC6uJmleno7x", "Godspeed", "Frank Ocean");
new Song("3xo4Q43ei0ypZOvd2W1IqZ", "Like You Do", "Joji");
new Song("6Vgtvd7I5yopJdBuxqjBd2", "Your Man", "Joji");
new Song("6cbsrCcgGstNCgWFKnrQmc", "Mr. Hollywood", "Joji");
new Song("7b2elHA9vOwpckUKm8SMyR", "777", "Joji");
new Song("4iVMoqS3oOXSiEAx0l2BWj", "Back in Time", "Healy");
new Song("5EpLeWSwqOG0mZW0R4WdKQ", "海浪", "deca joins");
new Song("07sLudIuDxe6EKiQHrJsu1", "Chinomoreno", "Point Decster");
new Song("1aHlu4Hd1MkThwbgJtJOGD", "Love Song", "IDLES");
new Song("1ggYjU6zdFHgANcku82boU", "Afterthought", "Joji");
new Song("3LueS3mbuB1yaJNN0Ale6U", "Avant Gardener", "Courtney Barnett");
new Song("3P4Ng8mn5frgNJEAwKmsa5", "I Hope They Play This In Toronto", "Kai Straw");
new Song("45IOlKX8MzjXibQP0ObDeG", "Patience", "Gorgeous Bully");
new Song("7tIFZKrcPgzNUKBEU3Dvkc", "Mi Chica", "Los Reyes del Falsete");
new Song("0OTtnwUO8natNWSwdZvXVF", "Inolvidable", "Ovy On The Drums");
new Song("1VZEFMJkZuppLl2PUsUkC1", "Television", "IDLES");
new Song("00l4b7ihmc0reIuQBSH9iB", "High Hopes (feat. Omar Apollo)", "Joji");
new Song("0pe4ZDlIQ3mo7pVJC4liAa", "Note", "Nat & Alex Wolff");
new Song("6HYm04mKq02OtLMf6sGEFR", "Caruso", "Lucio Dalla");
new Song("62FHlCqoihuvRCRQ9cWlTA", "Luces", "NORTE");
new Song("4KgTrzmfiWNcVneh2Dd1Ou", "Sometimes...", "Tyler, The Creator");
new Song("7LYeytL8R2fuqnsW1s0k86", "Phone Call - From 'Eternal Sunshine of the Spotless Mind'/Score", "Jon Brion");
new Song("74WjYdm3Lvbwnds4thYPUU", "Turandot / Act 3: 'Nessun dorma!'", "Giacomo Puccini");
new Song("69wePb2qJWL7zgGRmge2Um", "Wall Ball", "Art Contest");
new Song("3vMb4PJslZDQMvsJ71AAmG", "Pickpocket", "Vanillaroma");
new Song("2htAwAC9v2lne771rBnzSJ", "En Mi Viejo San Juan - Versión Trío", "Javier Solís");
new Song("7ffkdwy4EvMSeUnPVSyqqw", "Azul", "Zoé");
new Song("6s1QAIr9vmYiEelpl5lFew", "East", "Rosetta");
new Song("7pmW5pnmt4neelpBilTJHd", "This Old Machine", "Coconut Records");
new Song("0ND6kttSpMIwmh7mkFgfYA", "Golden Choice", "Little Jesus");
new Song("30bqVoKjX479ab90a8Pafp", "Star Shopping", "Lil Peep");
new Song("3qItYNPhAFxQp4QLN1pikP", "Más o Menos Bien", "El Mató a un Policía Motorizado");
new Song("1h60uIZlSuKwKwreUE3w1N", "Más de una Vez", "El Shirota");
new Song("1bWEngw5tAF7vWByrf5Oy5", "bloody valentine", "Machine Gun Kelly");
new Song("0UNTF1iCMdGCxc4HV3ZUTH", "Solo Quédate", "Acto Catártico del Colectivo Versátil");
new Song("0w2kfnU1PFKxjmZFQ1J1X8", "Overthinking", "Acid Ghost");
new Song("1c7LdDERW45Sn0zzxFzH5E", "Chico", "Art Contest");
new Song("28PORYgAQ5vrbwtobRlCoq", "A Felicidade", "Antônio Carlos Jobim");
new Song("2MS98sTzH3OsaFS4ZKzqPK", "Navy Blue", "The Story So Far");
new Song("4Q66chx9WzqWcLItXoZ5r4", "Cherry Wine - Live", "Hozier");
new Song("7wKEBslPrHvbP2iL4z8cG2", "Carl Sagan", "Los Natas");
new Song("1zvdOpnTT7U3IQXq6vJHvJ", "Is There a Place I Can Go", "Trudy and the Romance");
new Song("1IslZs9FYFhwH7mQ9C0Yt0", "Heir Apparent", "American Football");
new Song("1JqcZQCnxjDOfZZwQidb1H", "Broke", "Samm Henshaw");
new Song("2ov7jzg8iAWWlpZuaXPUBK", "Dormir Sin Coger", "Arroba Nat");
new Song("4miKDdaWW78mKwx6TIvOa0", "We Might Be Dead by Tomorrow", "Soko");
new Song("0Xcy81PsJCOO6mhLZaQyQ4", "Perfecto", "Mac Miller");
new Song("0iBOLnepgpMhH4NinExjCn", "Musica è", "Eros Ramazzotti");
new Song("1AMBOSeXi1bqHDTi8EeSR6", "It's Not You It's Me", "Coconut Records");
new Song("1BViPjTT585XAhkUUrkts0", "Seigfried", "Frank Ocean");
new Song("1IdZvb2XK8NmsovQlV6CPn", "Be Yourself", "Frank Ocean");
new Song("0x2VgHoxUxKFbIUqQur8Fe", "Sino", "Unique Salonga");
new Song("6V2QgOIMT94HhsfeIVbbZm", "Manila", "Maribou State");
new Song("3eddddUsVZSYgk9Vs9a4L5", "Tristan & Isolde: Isoldes Liebestod", "Richard Wagner");
new Song("4U09Dsa20zQ5ducUTJEmB8", "La Asimetría Según Cardin", "Tino El Pingüino");
new Song("1xYBeQ5u8uaJ3oBWktjGyJ", "Acurrucar", "Ed Maverick");
new Song("65II7NFnz2mjfaCEKeJEux", "Enemy", "Kai Straw");
new Song("4KlbJch4OzwdMEWGVECEtJ", "Kathrin With a K", "Super Whatevr");
new Song("76NtMPMpA6fuUH4euMYZoD", "Buenos Genes", "Rels B");
new Song("1ZMiCix7XSAbfAJlEZWMCp", "Falling", "Harry Styles");
new Song("5jrTiIhaP25UPGo54V5HL6", "No Hay Futuro", "NORTE");
new Song("0lppL7OMGEnzruhQUT9fZq", "I'm Not Real", "Mac Miller");
new Song("0oH6dm5Mc0zzUfe8NERSvL", "Breathe Life", "Jack Garratt");
new Song("1LD52Nzt9wg1vB3F6gelPH", "Undo", "The 1975");
new Song("4e57YPpyBpWetYWk2weJt4", "Lluvia", "Loiis");
new Song("5rfbqI2j7IN7oNx6LSq7pN", "Roma (LRDP Maqueta)", "Sabino");
new Song("72Qo3U5apeuv91j9BEqJBM", "I Don't Wanna Waste My Time", "Joji");
new Song("0khJmjhaoYJ0KsVDmOqXZb", "Minimal", "Bo Ningen");
new Song("0okvm6ZcKwucPFK0xhOjsM", "Arrúllame", "NORTE");
new Song("6W4no5exe0B9TwGRhn98xr", "Petricor", "NORTE");
new Song("04hlcjXK4ix4WTUBL1p30K", "Cologne", "Haux");
new Song("08jAird2h7gXmJxqJtdDeU", "A", "7");
new Song("397rM4wePe8bPJSMAwFNUO", "Good Times", "Matt Duncan");
new Song("3uYrVtgRuz4XiOOXDV805X", "Dreams", "Nuages");
new Song("47w6S27JF4Zvrz1Wd6R66Z", "What Kinda Music", "Tom Misch");
new Song("5fladZOvaBFmoI2NvBidao", "Intro", "Klaatu Suuns");
new Song("6AeyHqzNHJthYJbn0tvJ4b", "You've Lost That Lovin' Feelin' - Single Version", "The Righteous Brothers");
new Song("6tgwPZ3HmB5ncM0EU3xgx4", "Solo para mí", "Never Seen Autumn");
new Song("7ayuuCBLywECYE5cfv9gXy", "We Will Be Alright", "Two Feet");
new Song("4w9TBRGhvbhiLQB8jVCusl", "Cheetah Tongue", "The Wombats");
new Song("3YnwIp2b99p3e5dsFTXIIx", "Dunno", "Mac Miller");
new Song("56wQddZqh3S2y2TGhgEyQw", "Mine Will Always Be Yours", "The Moving Pictures");
new Song("22seP38foydqUMp5Fvkcjm", "Inolvidable", "Reik");
new Song("2HngDESphICt87xLY9LRnA", "1000 Boys", "Matt Duncan");
new Song("0EA2RhRHL4KWeNa7JfD1Yw", "So It Goes", "Mac Miller");
new Song("0h4kOUA5ec7k7oW8pEeYnC", "Lonely Lullabies", "Kweku Collins");
new Song("0znhPiQvvLfOxDB0cJWu6z", "Pasado / Presente", "NORTE");
new Song("1ErrkKi89V68HHsyUizbJA", "Wanderlust", "James Bay");
new Song("1KIFzfieBfkpYL90sLJ3D6", "Real Love", "Sugar Pine 7");
new Song("4tlqYj5LHUpXNBN1F0Iw5p", "Lo Que Construimos", "Natalia Lafourcade");
new Song("48O0GrGJWml3DzHhC5sJ7a", "Karma Chameleon", "Culture Club");
new Song("4iM1CuO0w90lO6iTSh4oxE", "Eeeeee (Interlude 1)", "Estado Lírico");
new Song("2VhXTSo5qSsvoLWn0haQcv", "Mi Tierra Veracruzana", "Natalia Lafourcade");
new Song("1SpJusI8TUxRQboKRdi16s", "I Want the Night to Stay", "Matt Duncan");
new Song("2H7pbA1dej41MIvXcrsnqU", "Caruso: Caruso", "Lucio Dalla");
new Song("1z3pPyR0cbquVYWZOHkox9", "Meanstreak", "Matt Duncan");
new Song("4SkTfsjWUy2rp40d2Ayfmv", "Tired Boy", "Joey Pecoraro");
new Song("1OBcvtUXOkvlbkA13CLvk4", "Corazón y Cabeza (Interlude 2)", "Estado Lírico");
new Song("6YV0Juh7ByWyT6A2qYNj7S", "Princesa Tibetana", "Timbiriche");
new Song("6lv5xJNWI2fYwjrPG4KFSe", "Beacon", "Matt Duncan");
new Song("35LSQvlXsCQLaBEAe1gTR9", "Holy Mother", "Eric Clapton");
new Song("4aE95aFiLdGQWb4nQ7Ktut", "'O sole mio", "Luciano Pavarotti");
new Song("56tLr0CatthOUDyrmu0gZo", "My Way", "Claude François");
new Song("6DFpH1EwJp05AGgqX5OWZO", "Puritan Heart", "Matt Duncan");
new Song("3BxYVmk1hvKX3Lef68FlGb", "Köln", "Corey Kilgannon");
new Song("3iRiQJsQmH0yPIOJn3Y4WQ", "Heart & Arrow", "Matt Duncan");
new Song("4INpamUxVd94SwNoFdiRzP", "Panis Angelicus", "César Franck");
new Song("1gsMCkVQoG7YXt1CqQ7ZiN", "The Bend", "Born Without Bones");
new Song("0tTbk9bpoFRDa19eVghS4d", "Caruso", "Luciano Pavarotti");
new Song("0tyWs7VaLmVvUkFXd9nyfj", "Cuando Me Enamoro", "Andrea Bocelli");
new Song("6ZDQSjfR7gk326zR1B8JSg", "Gitan", "Garou");
new Song("6hABrbNtm1EgnFPQ1qTH8C", "Turandot / Act 3: 'Diecimile anni al nostro Imperatore...Padre augusto'", "Giacomo Puccini");
new Song("3SH5hjBZnY4DsIy40lvlzP", "海浪", "deca joins");
new Song("4aYRqKIdN8605wm4p3tGNa", "Caruso", "Andrea Bocelli");
new Song("0vlTyXdxncOF0RRKTMWfpo", "The Illest Villains", "Madvillain");
new Song("1Frg5YRCsuBocPoDwnKSvs", "Buongiorno a te", "Michele Centonze");
new Song("25ZYvZ2qFw7XCu8nzUxxmU", "Rigoletto / Act 3: 'La donna è mobile'", "Luciano Pavarotti");
new Song("3LwHc6Z7EYszoyM6Duucbr", "Fall On Me", "Andrea Bocelli");
new Song("51GYRkJC8iowN0DHc18UlC", "L'anno che verrà", "Lucio Dalla");
new Song("692C4fgt86NVLGwKXe4KCs", "Hasta la Raíz", "Natalia Lafourcade");
new Song("6H8R62wUNjDdRBgsF9DXxg", "Sembrando Flores", "Natalia Lafourcade");
new Song("6OzcxsMLy6vKFt3llB2Kqx", "Ragazzo Mio (Danny Boy)", "Andrea Bocelli");
new Song("6VZB0ttlqGjpGMAcaomXh9", "Sous le vent", "Garou");
new Song("6hjeTjKXbxYrhj5zMNZYaG", "Real Love", "rei brown");
new Song("6zqK3fE8uCRLpZLUj9VGci", "Peer Pressure - From 'Eternal Sunshine of the Spotless Mind'/Score", "Jon Brion");
new Song("7MRyru6giOwdtFYL5KQEVq", "Seul", "Garou");
new Song("7fLWUJpyNbEfrLFKLo8ymN", "Belle", "Patrick Fiori");
new Song("7i5AXmrPAKPK2zkjrqRDy5", "Dormi Dormi Lullaby", "Andrea Bocelli");
new Song("6VzcQuzTNTMFnJ6rBSaLH9", "Fine Line", "Harry Styles");
new Song("165cwz4wGlGz0uDBhxdKLY", "Right", "Mac Miller");
new Song("2jHnuEYl7x1EtG4NGDDkdN", "Mexicana Hermosa", "Natalia Lafourcade");
new Song("5Gd6hn16MIvP3Tn1NzAuas", "She Was", "Serotonin");
new Song("6l3A2EWZSOA8LTMmzRCyD3", "Dream House", "Deafheaven");
new Song("6U29ufMcZrqX0vLVyLTPlA", "Having No Head", "The 1975");
new Song("1SXzI5Rnid2ApgNQPmROLm", "Muchacha (Ojos de Papel)", "Almendra");
new Song("4NGs8bDJyNV1dgnAbUVZS6", "The End (Music For Cars)", "The 1975");
new Song("6KAf0R3bt14ZbVVUPaVSQQ", "Streaming", "The 1975");
new Song("3qZwJ1SiY32JW70JqgiFbY", "The Birthday Party", "The 1975");
new Song("76ej7aOQU1tfdzkE3xQ6HS", "Arruinarlo Todo", "Molinette Cinema");
new Song("3mRWkQTwau3cl5u2WYE2pt", "I Think There's Something You Should Know", "The 1975");
new Song("6OPOa3qlKoDUzGpS8MrcLi", "This Must Be My Dream", "The 1975");
new Song("1C5utO1I8FoSIn6g1R5DAZ", "If You’re Too Shy (Let Me Know)", "The 1975");
new Song("4gV209d7WZmbrIZ5jgu30A", "Sound & Color", "Alabama Shakes");
new Song("60uaRxHbP2XSgiysI6QYAt", "Postales Negras", "El Mató a un Policía Motorizado");
new Song("6c07FQryyVnmfFUuECzRvV", "HNSCC", "The 1975");
new Song("7tNzSvipxHL4M6pKtv8CNw", "Golden Chords", "Deakin");
new Song("7BJny7nQN5bY4EeGVU3kj6", "Head in the Ceiling Fan", "Title Fight");
new Song("3wFPsw1WQJevCFoKpoLyTF", "The Birthday Party", "The 1975");
new Song("5FbfZj2ZyTSu6RNeJ2Q0bj", "Frail State Of Mind", "The 1975");
new Song("1JCCdiru7fhstOIF4N7WJC", "Amnesia", "5 Seconds of Summer");
new Song("2M4iGyQTIJISEioeVz43vy", "Nothing Revealed / Everything Denied", "The 1975");
new Song("3ERlkLtr5K5C7VUqlDcNSR", "People", "The 1975");
new Song("5k8eNtmqlKe21qjIFIp1Du", "I. Flight of the Navigator", "Childish Gambino");
new Song("5rhMc6IqSdVsyF7bRieSTc", "Good News", "Mac Miller");
new Song("6yTsxAaH03k68AQtErgU7h", "La Casa Fantasmal", "El Mató a un Policía Motorizado");
new Song("7gamP4sRTXxfqKblTVYmci", "Anobrain", "The 1975");
new Song("1GhiA5XvAywQNma9eK7XL4", "Friendship", "Big Big Love");
new Song("1Q7iiCL2o5MyLI0wxEpryG", "EAST", "Earl Sweatshirt");
new Song("5ATPYuah4Gw0gw1BpsiG3S", "Coffee", "Copeland");
new Song("5sKYBOxkgrwGvTsbdOWSsW", "Unrecorded", "M83");
new Song("7xlFGu8Xdu0OW1jEkiwi9t", "Buscando Más Allá", "El Mató a un Policía Motorizado");
new Song("37PSljWwMyg3JhqWma3Wai", "Lostmyhead", "The 1975");
new Song("0SyY4pnirW6dDPMe32izRb", "Woods", "Mac Miller");
new Song("0YtmwGMUPaBIEuJs0FNiDm", "The 1975", "The 1975");
new Song("19YUY78DXVzYnQwxu1letI", "Strung Up From the Sky - Live", "Pelican");
new Song("1YIy56OJyVpuzoTQYiqkpg", "Hand Me Downs", "Mac Miller");
new Song("1egM7cqkpt2lSH5b6IZrV4", "Birds", "M83");
new Song("1fvRueeK5f60hkG1VzoXXq", "Victor's Piano Solo", "Danny Elfman");
new Song("1jWoeUIvNJniadGbeTj03X", "Playing Around Before the Party Starts", "Childish Gambino");
new Song("2jLmmcdh05eWfafvZENIbb", "Somewhere", "deca joins");
new Song("3tk5DaXxxUoV7b5nOdCDBv", "Jesus Christ 2005 God Bless America", "The 1975");
new Song("0cDvVjiJ8iKCYcypWJ71ay", "Doors", "Mac Miller");
new Song("3eUYUFu7PhhxWSIV8c3uX6", "Mera Telos & Letpig Adventure", "Incendios Forestales Del Viejo Continente");
new Song("6OGOOLwgqrlVdwIuPbbz3r", "Pantera", "Jesse Baez");
new Song("0zBkMWVgXo7prFSw1YJRn4", "Rush", "Once Upon a Dead Man");
new Song("1B6CHcim4uHt8NIy1Bamqc", "In The Ground", "Illiterate Light");
new Song("3FlIxaICsgxU2lQg029fKp", "I Wanna Leave America", "Illiterate Light");
new Song("14FVgBsjyLMys6KZq8Pcon", "Last Call For Austin", "Felly");
new Song("1yiQ4iClDVSJemlFoLk3h2", "Years Gone By", "Avantdale Bowling Club");
new Song("2ET3PMTWQcO9B01Bt2epGu", "Alguien Que Lo Merece", "El Mató a un Policía Motorizado");
new Song("3u0kNxqOOC8SdoODpkmoZO", "The Loser", "Zach Farache");
new Song("4LT3jD9UcmFRKZiyuYlp7n", "If It Don't Work Out", "Anthony D'Amato");
new Song("3djWN7th03XZtmF5s3C1Lv", "J'OUVERT", "BROCKHAMPTON");
new Song("47YtggTyUlgaR9Z8GIbqsm", "Magic", "Kai Straw");
new Song("1D1YNQgrvte4jgJVUUAOsx", "Te Boté (versión bolero)", "Los Rivera Destino");
new Song("2Wl4MbBRtan8gr0C8qUSGT", "Why Do I Wait (When I Know You've Got a Lover)", "The Zolas");
new Song("0G86wTwna5K8zwpiukp4Qk", "New Soul", "Felly");
new Song("2PHQr9JMiepZ1GRh4wWxpg", "We Appreciate Power - BloodPop® Remix", "Grimes");
new Song("3EAUSlUzVTLhxLn8Fhpz5V", "Irresistible", "Deafheaven");
new Song("3Wjx07xPRXTRRtQToKnuYD", "Home", "Aaron Taylor");
new Song("4YwDTVCOnQkRgDcqZVtMiH", "Minyama - Demo", "Klaatu Suuns");
new Song("667BMtYteOnldcQWsQYehG", "So, Soo Pretty", "LANY");
new Song("6BAuys1bPzAqPUEzZ0OAA5", "These Drugs", "Sugar Pine 7");
new Song("1PdHorDs2MY7Npj8VQynSn", "Thug Tears", "JPEGMAFIA");
new Song("2wbpmuS49PoYDfmjETmK0v", "Empezar, Pt. 2", "Sureste");
new Song("4OHGeA6HhKm4mSO97m6wDs", "Better Than I Used To", "Illiterate Light");
new Song("4wuu0v0TsGf22iYAgIcKlb", "Altered State Of Mind", "Milmine");
new Song("62ljuuXo0zrcrtJnnOhfxT", "Dear April (Side A - Acoustic)", "Frank Ocean");
new Song("7BCzMKLKQwVSLtZcDGJTJt", "Floating", "Mac Miller");
new Song("01iuIXKIgj5F8UZm057IaY", "Snippet", "Nils Frahm");
new Song("0dJxSQHejGq0ID98PGqVLN", "Keep In Mind, Transmogrification Is A New Technology", "Mayday Parade");
new Song("3naMieRVMmNg3sCRDLbtlZ", "Sober to Death", "Car Seat Headrest");
new Song("45S5WTQEGOB1VHr1Q4FuPl", "Golden", "Harry Styles");
new Song("5jeDAq40nB1ZCTqZAZIlm6", "Vincent", "Car Seat Headrest");
new Song("7rQh2rZmHJKn79KfnpffAE", "Carolina Lorelei", "Illiterate Light");
new Song("2os0aK782bakCPmjow0SU0", "Drunk Drivers/Killer Whales", "Car Seat Headrest");
new Song("4BGZF4oLbTL0pWm7C18pbv", "Scared To Live", "The Weeknd");
new Song("6UelLqGlWMcVH1E5c4H7lY", "Watermelon Sugar", "Harry Styles");
new Song("7rlRddHxJKuq2VJN9zVfyb", "Silver", "Big Big Love");
new Song("7pPtLFfse8FnOc8GJx9GEj", "Puentes", "Cazamos Cometas");
new Song("6SQLk9HSNketfgs2AyIiMs", "She", "Harry Styles");
new Song("0QUnzLeB2USzFv8OqJe8S8", "Olvídala", "Binomio de Oro de América");
new Song("1qiJs6Nolt9y30Lov0HmPF", "Existential Crisis", "Illiterate Light");
new Song("32NHNYWOYKrqWib9O7kdgQ", "Carreta Furacão", "El Shirota");
new Song("3WS9ak7rsRENV3cV9VRf2D", "Flashpoint: Catheter", "Cap'n Jazz");
new Song("3orEOtd8CPL8GFlpRpKuoE", "Faith", "The Weeknd");
new Song("3yLaz5KsWORNRQvActpZKY", "Without Walls", "Illiterate Light");
new Song("4jXl6VtkFFKIt3ycUQc5LT", "Circles", "Mac Miller");
new Song("4ue1k6IIQFd0BAAiOF50yi", "Honestly?", "American Football");
new Song("5JiH89mHrv9oWHlD0T326z", "To Be So Lonely", "Harry Styles");
new Song("5P3yUXUC9rZPJPNmYGKEAz", "Goner", "Twenty One Pilots");
new Song("6men4y6a8QuGtE5qkFkOgR", "I. The Party", "Childish Gambino");
new Song("0WO2YHUoVwPsIk6Gvv79a5", "Cutlass ('96)", "No Somos Marineros");
new Song("0hK93KD6Y0j9giUGh4Valj", "Ours", "Taylor Swift");
new Song("4YHLL9Wqh9N1RZTExS9olP", "Great Fairy Fountain (From 'The Legend of Zelda') [Piano Etude]", "Erik Correll");
new Song("6Rs79BpoJYdQpbMXP41I3B", "You See Me", "Childish Gambino");
new Song("0304W5CLkIPtsw5UzK6Enr", "You Know I Should Be Leaving Soon", "American Football");
new Song("0udOCZp7yk0Ml92C0k8H8D", "That's On Me", "Mac Miller");
new Song("1pKziOaiDCnrgMOqzQMtu2", "I'll See You When We're Both Not So Emotional", "American Football");
new Song("2FHSqmFABkeukiKUBAtnPd", "Wish I Didn't Have Any Problems", "Illiterate Light");
new Song("2IOFZdYYkFxEHVz1w34PoL", "Cherry", "Harry Styles");
new Song("2KtvPGe3KGRkI7WoCKGcv8", "Blonde Sun", "Angus Maude");
new Song("2YSdttfME0OmOj9mPwHFIK", "Corn Maze", "Malibu Ken");
new Song("2doQ4LEtEDbL3cIPEeHP1E", "High to Death", "Car Seat Headrest");
new Song("35xnCYrjXbuqhgl7E0rhck", "Stay Home", "American Football");
new Song("3LdT7JYN6LCXUFnh0uaxgp", "The One With The Wurlitzer", "American Football");
new Song("3hEtfSqTlPIAKlysBs1lZl", "Black Habits I (feat. Jackie Gouché)", "D Smoke");
new Song("3jjujdWJ72nww5eGnfs2E7", "Adore You", "Harry Styles");
new Song("4EQlTA60UgWuSrc1UfWUyQ", "Nervous Young Inhumans", "Car Seat Headrest");
new Song("166T5iL97Xaxb35mCV6abl", "Cuando Piensas en Mí", "Tino El Pingüino");
new Song("0G0NKx220sZpjXC4LSoCkA", "Honeycomb", "Deafheaven");
new Song("26AYR77170U49cMcXB7aRV", "Feeling This", "blink-182");
new Song("1CIuTzWLQ3sxScgFJzUhWT", "Mi Tierra Veracruzana (feat. Los Macorinos)", "Natalia Lafourcade");
new Song("61HBuVsspScrGUobbfmhOT", "The Summer Ends", "American Football");
new Song("2hwOoMtWPtTSSn6WHV7Vp5", "Blue World", "Mac Miller");
new Song("1yFpfstp16ZQjB6B8tS448", "Muchacha II", "Lng Sht");
new Song("5yLwrRhD6qxPM0qmE97j2a", "Te Vi Pasar (feat. Los Macorinos)", "Natalia Lafourcade");
new Song("7h9bpmFb7knrg8rc0inU9j", "Yours Truly", "Klaatu Suuns");
new Song("1OuN92HcVG6NVpWbeESNB3", "Everybody", "Mac Miller");
new Song("1kwnxJNVl7cwcU98RvMBaR", "Surf", "Mac Miller");
new Song("3Qa944OTMZkg8DHjET8JQv", "Woods", "Mac Miller");
new Song("3WfSNAoj2D8C9noPSGZZFM", "Complicated", "Mac Miller");
new Song("3e0yTP5trHBBVvV32jwXqF", "Anna Sun", "WALK THE MOON");
new Song("47A4a2ZxJaZz5nBME2HtXs", "Grief", "Earl Sweatshirt");
new Song("3QFu0dgZ3ivX3E3i0lvifS", "My Nights Are More Beautiful Than Your Days", "Current Joys");
new Song("4dV4G96hqT5qCU9v7JBCk2", "The Sailor", "Rich Brian");
new Song("5TzlpafHpevHNyIvEvjljO", "Evoca", "Tino El Pingüino");
new Song("5BNZcuyCkcBNIhF2DmQlWf", "Fractúbela", "Tino El Pingüino");
new Song("2RPbEp0DyBVlkRvvYKopO7", "Wat's Wrong (feat. Zacari & Kendrick Lamar)", "Isaiah Rashad");
new Song("3R8CyhJfVjvgIROd5RSGhQ", "I Can See", "Mac Miller");
new Song("6EToxVugFcoi0f82FBpbdf", "Rocío de Todos los Campos (feat. Los Macorinos)", "Natalia Lafourcade");
new Song("6GFMVhlYtV6BifvWjZ2b7j", "Mexicana Hermosa (feat. Los Macorinos)", "Natalia Lafourcade");
new Song("6UB0oeQixDMtuQalt0QFS0", "Tonada de Luna Llena (feat. Los Macorinos)", "Natalia Lafourcade");
new Song("6VNjaZmWzm0aRXeBE1B5mM", "For Sure", "American Football");
new Song("10HQmG706HZtAhXRypWw01", "Son Amores (That's Amore) (feat. Los Macorinos)", "Natalia Lafourcade");
new Song("1DWZUa5Mzf2BwzpHtgbHPY", "Good News", "Mac Miller");
new Song("6WrI0LAC5M1Rw2MnX2ZvEg", "Don't Start Now", "Dua Lipa");
new Song("0WOvSEVpUGkNufX0w0M06F", "13", "LANY");
new Song("0u2doa7efwRRUk6vAIKj94", "Operación Desahogo", "Tino El Pingüino");
new Song("1AzqpMy3yLYNITSOUrnL8i", "DIET_", "Denzel Curry");
new Song("1EALzILzmIPtRIvYyo6Lwm", "Fill in the Blank", "Car Seat Headrest");
new Song("3ClBKQkKoaUQ6UOhe2xlJK", "Good News", "Mac Miller");
new Song("2Yv2mHzr5AQavVdwQjEokV", "Hand Me Downs", "Mac Miller");
new Song("4ZDyo32Vg4avIKHaDfZSOg", "Never Meant", "American Football");
new Song("26G5nmIx7Yvq79bIIluyZV", "Once A Day", "Mac Miller");
new Song("76nlq5gomu49Yn5dfmtv0C", "One", "Sleeping At Last");
new Song("15UttZPJXWsb1fSLwNSfov", "Five", "Sleeping At Last");
new Song("1lSnBlAErRss6asu9Y5HuA", "Eight", "Sleeping At Last");
new Song("3HGKzDBC6MfnJtcCRi7xB3", "Nine", "Sleeping At Last");
new Song("62CprXvSWsKBvYu3Yba55A", "Two", "Sleeping At Last");
new Song("6ECxq5Sh1ogq6oHDRUVmV2", "Three", "Sleeping At Last");
new Song("6XvzSF3NDwOKP6RF0YmXEU", "Four", "Sleeping At Last");
new Song("5os4iDInR4chqaCdXi895k", "Six", "Sleeping At Last");
new Song("7zbFh74zImpQho3btxuANN", "Seven", "Sleeping At Last");
new Song("5cxE8QZLrhP3OQjslZ8Lux", "Salven la Torre del Reloj", "Sad Saturno");
new Song("6CrnvqCxBKVWahSiQwOesM", "Hands", "Mac Miller");
new Song("45b0d0jbSIyzZbZSYsJw1Q", "Butternut", "Healy");
new Song("65LwyLdAcH7a5LocXHkX41", "Ironias, Anhelos y Frustraciones.", "Sureste");
new Song("0lJ8a4Cl1brPVARa0WLyOX", "Intro", "James Bay");
new Song("2DkZisoN9h1dLa8Sn5sx0n", "Bitter", "Palace");
new Song("1OubIZ0ARYCUq5kceYUQiO", "Congratulations (feat. Bilal)", "Mac Miller");
new Song("3wczwhLbWHPNXIL1fPd8qe", "María", "Cazamos Cometas");
new Song("4iABNEtdO5AY6UPL2HGlDI", "El Salvaje Ben", "Sad Saturno");
new Song("5oK98mpTJSU0iqLHN1hZ3y", "22 (OVER S∞∞N)", "Bon Iver");
new Song("4YwNf1fLZt9IQhJeHNWfBi", "Intro", "J. Cole");
new Song("4m85osQ5pt9P0AroPYMObk", "Five Silent Miles - Demo", "American Football");
new Song("4KbGAETHmVqRb693Ue7F6N", "Let's Talk About Your Hair", "Have Mercy");
new Song("0E8q2Fx2XuzXCO2NSAppkR", "In A Sentimental Mood", "Duke Ellington");
new Song("5bJ1DrEM4hNCafcDd1oxHx", "Self Care", "Mac Miller");
new Song("0D666EMLUFA9Ms5HZdzhhI", "Interlude", "James Bay");
