class Song {
    constructor(uri, name, artist) {
        new RandomObject("song", name, artist, "", "https://open.spotify.com/embed/track/" + uri, "spotify:track:" + uri);
    }
}

new Song("1wpin6CIQlmEUuZvALQSVw", "Aquarium", "Mac Miller");
new Song("4CAFjRhubtiR8M3z4qbc2W", "Navy Blue", "Hasani");
new Song("6pwh8jxrpOoXAXhjAhIvFE", "Czech One", "King Krule");
new Song("3usBViVaNvJsFkFxUpOxCP", "Never Break", "Langhorne Slim");
new Song("3EjxAbEOH28icEK1ZFOUSh", "Essa Tal Liberdade", "Só Pra Contrariar");
new Song("3kJFOAzggfdQh8JmukWWq0", "Are You Coming with Me?", "Kai Straw");
new Song("4WHmafrJ0ANeLFf7UlXjiM", "Messed Up", "Verzache");
new Song("77gQSJlncgT3HWmBfy9CQ9", "Aire", "Nicole Horts");
new Song("3M8FzayQWtkvOhqMn2V4T2", "Lean on Me", "Bill Withers");
new Song("67u55G1oKniIsCBQoM43h1", "Spaghetti", "City of the Sun");
new Song("1bRrJaO9IHxsx8OY3ly5di", "Púrpura", "Nanpa Básico");
new Song("0gn5HTzwrLAw3KLuodW5vo", "Ballroom Floor", "Oberhofer");
new Song("1gTFwhHHsk4LwKGcLLe7r5", "Dmi Thing in Which New Information Is Introduced", "Jon Brion");
new Song("4M9gZEtOSf2I1hyGNvZbpF", "Take Me Home", "Silver Rose");
new Song("06yxqYBEv95RTvSTWUOOcm", "Crimen", "Silver Rose");
new Song("0IHWITC8b1u4edMKWZaJ2K", "Sueños de Amor", "Silver Rose");
new Song("6D43oUO6nImERk2psfXdNY", "Afterlife", "Arcade Fire");
new Song("7dXyQvTkoiNVtsXAgFTXmL", "Bermondsey Bosom (Right)", "King Krule");
new Song("07UjHiSAzFsXY1FpG7lErp", "Sun Halo", "Oberhofer");
new Song("5jSBnH9NyaNP5zdSB3pwgu", "Gimme Love", "Joji");
new Song("0yDO4PTWyBeGtR35Q3Qt1a", "El Balajú / Serenata Huasteca", "Natalia Lafourcade");
new Song("2LpcTDgPrMexPloLcHsSWl", "A Slide In (New Drugs)", "King Krule");
new Song("37UNeKSzilH978feP03T04", "Reconcile", "Jon Brion");
new Song("5Pd4DM7B4xm073ZK6840NU", "I'm Alright", "Silver Rose");
new Song("5tRFtEiBSsBBCPHdwkfGp1", "Noches", "Silver Rose");
new Song("67vV72Oo7aty9EqYj1mwlR", "Perfecto Miserable", "King Krule");
new Song("6yzzno5cXBkh5c6UzRxcyM", "Lady Bird", "Jon Brion");
new Song("38TrmGyKtQ4r9JxEfk8xlT", "Emergency Blimp", "King Krule");
new Song("3vMb4PJslZDQMvsJ71AAmG", "Pickpocket", "Vanillaroma");
new Song("04hlcjXK4ix4WTUBL1p30K", "Cologne", "Haux");
new Song("0GAE689kVy7sFT2QWZH1Xa", "Start", "Frank Ocean");
new Song("0GUF4GxxXQDuyLNp0Wqa1W", "Where I Left My Heart", "Silver Rose");
new Song("1IF5UcqRO42D12vYwceOY6", "From the Dining Table", "Harry Styles");
new Song("1LD52Nzt9wg1vB3F6gelPH", "Undo", "The 1975");
new Song("1ko2lVN0vKGUl9zrU0qSlT", "Just the Two of Us (feat. Bill Withers)", "Grover Washington, Jr.");
new Song("25r99eqlm3lHGnZHoeg7YX", "Supersymmetry", "Arcade Fire");
new Song("2CfrVHG9aS3HWaVLZk8wZf", "Rainy Taxi", "Spoon");
new Song("3AJwUDP919kvQ9QcozQPxg", "Yellow", "Coldplay");
new Song("3YnwIp2b99p3e5dsFTXIIx", "Dunno", "Mac Miller");
new Song("4LX270g9HEBkA0qYtGAel8", "Los Bajos Fondos", "No Somos Marineros");
new Song("4ld9QYEpwDD3m8gGfUn19Z", "Porno", "Arcade Fire");
new Song("51R5mPcJjOnfv9lKY1u5sW", "Never Meant", "American Football");
new Song("57t8BTQgH5qfHQXosfZ2pk", "Exploration", "Kevin Penkin");
new Song("5EpLeWSwqOG0mZW0R4WdKQ", "海浪", "deca joins");
new Song("5o4ZFpzx0AMh213vB8cfR1", "I Need a Girlfriend", "Netherfriends");
new Song("5v9GvZIJuD7QAkGIO8CHpm", "Vidual", "King Krule");
new Song("63fj7dR4QGRHDHKZStUuAY", "Bad Things", "Milky Chance");
new Song("69wePb2qJWL7zgGRmge2Um", "Wall Ball", "Art Contest");
new Song("6R5JpLDVRgRI6P2OQCjA4n", "Drifting Away", "khai dreams");
new Song("6ZDQSjfR7gk326zR1B8JSg", "Gitan", "Garou");
new Song("7LBdv0ek7Tj2s0bgxmlrC6", "CALLIGRAPHY", "Saba");
new Song("36YLqJHsNHHODwX5gDPEBb", "Settle Down", "The 1975");
new Song("2uo7zovExT4d5xaAIcdoQI", "Aka", "Bo Ningen");
new Song("29XzxmYd35qr4pxfydaOIN", "Cracked", "The Jesus and Mary Chain");
new Song("4VPzrser2mIjpNwaChxkWo", "Ambition - Single Version", "The Jesus and Mary Chain");
new Song("0QQviRjnsuP04U9r75fANz", "Something's Wrong", "The Jesus and Mary Chain");
new Song("5xnK3NwAHclYaQl8fGiCtZ", "Taste the Floor", "The Jesus and Mary Chain");
new Song("1LwP9g1Hjbs64jXM2Qsxry", "Just Like Honey", "The Jesus and Mary Chain");
new Song("5Hd5ndh1IXwC236KD7iolG", "Still Down", "Prince Fox");
new Song("0MeBMmSQvrCdNHpWA2wJSi", "Go Ham", "Prince Fox");
new Song("6PnTgx9lyvLGIcPnroCvc2", "Dior - Bonus", "Pop Smoke");
new Song("4Tc9PHEoeP17PQj3OOKXPu", "Diana (feat. King Combs)", "Pop Smoke");
new Song("3NWrHCwvyII4fTx05PN3IO", "Enjoy Yourself (feat. Karol G)", "Pop Smoke");
new Song("1JDhNQ0oOT7XpclZn3aQ8F", "West Coast Shit (feat. Tyga & Quavo)", "Pop Smoke");
new Song("2FhEj9lvEIaJihjFprRrGt", "Snitching (feat. Quavo & Future)", "Pop Smoke");
new Song("7sjFIZ1g5QLJLGja3k592K", "44 BullDog", "Pop Smoke");
new Song("0PvFJmanyNQMseIFrU708S", "For The Night (feat. Lil Baby & DaBaby)", "Pop Smoke");
new Song("1GajoGGolEncxGXops1feL", "smile more smile more smile more", "HONNE");
new Song("3vdJRIZ5GJkV0fAzmpGfjh", "gone gone gone", "HONNE");
new Song("4fCDCGt0Dzs6DFUNaMhB94", "s o c i a l d i s t a n c i n g", "HONNE");
new Song("1WJNTBzGIcnkJMN77XJlW4", "one way to tokyo", "HONNE");
new Song("5Pw4Q2Z2NttJtISFFxe9MK", "la la la that’s how it goes", "HONNE");
new Song("0GPJSHYaXh8rZSSJoUMgyl", "free love", "HONNE");
new Song("1lNHWPDvKEbamKezpLq7HW", "no song without you", "HONNE");
new Song("3IgJKBFHp17VR403l5IZ24", "Humble Passenger", "Dr. Dog");
new Song("0Pus2Qc8UF9megtfDtzGFb", "Can't Remember", "Dr. Dog");
new Song("5mtMuFYG4y7SMp7ve7hmhP", "Rock & Roll", "Dr. Dog");
new Song("53VBHeVubEuMklPAcG5bbO", "Twilight", "Dr. Dog");
new Song("29s44hpjVtXWYLSll22BJk", "Phenomenon", "Dr. Dog");
new Song("3vzS1rOvhKNueWIatEoJ4J", "Distant Light", "Dr. Dog");
new Song("3ZtiIp8iTVohALZR4Uq8Jt", "Broken Heart", "Dr. Dog");
new Song("1Zjjl59MPvGqR5msmQexs3", "The Truth", "Dr. Dog");
new Song("3kR9tGgRmnmlh8Tcse6yR0", "Wanting And Willing", "Owen");
new Song("1pRZoMIHOUUlD7PuHnKPj6", "Headphoned", "Owen");
new Song("1WMiYq0i0WCuSXKvgcMKL4", "Mom And Dead (feat. KC Dalager)", "Owen");
new Song("5bS8TdUKIK7BIe6OW5oChr", "I Should've Known", "Owen");
new Song("4T0poWWtj4VDzdI0lwo3ms", "On With The Show", "Owen");
new Song("1mQdYflTN7nlQOugykBXtm", "A New Muse", "Owen");
new Song("4A20zsJWczv2DvHs5GsmJ4", "Lis dans mes yeux", "Garou");
new Song("5fazcQoRfYQke80bxgBWlj", "Criminel", "Garou");
new Song("5ln6N51J6r9zNZNcFPu1Xs", "Je n'attendais que vous", "Garou");
new Song("2al5FV7uw6bnJR7ncLfjz8", "Demande au soleil", "Garou");
new Song("7DS8wehdmjuDRxRnmwjWW3", "Que l'amour est violent", "Garou");
new Song("1LXa3V58PvzL7Gbmqsgt8H", "L'anno che verrà", "Lucio Dalla");
new Song("79zNZxDYDKxxFytspm35Us", "Cosa sarà", "Lucio Dalla");
new Song("39F11ECuniTKD93J7NxaNr", "Anna e Marco", "Lucio Dalla");
new Song("1E3Mfy16EcFl1r1fXCrp7N", "La Signora", "Lucio Dalla");
new Song("2MOdGiKqm8EJT2CxzpIjpo", "Stella di mare", "Lucio Dalla");
new Song("6QFJphsBSCncqEsthAmlWg", "L'ultima luna", "Lucio Dalla");
new Song("4IIXnqZUndaRlMwomxZwIr", "Hechizo", "Heroes Del Silencio");
new Song("1sgk7dkImoLiq4XZU8JZE2", "Senda", "Heroes Del Silencio");
new Song("40FYFRru7SwWt61q6OEUjK", "Malas intenciones", "Heroes Del Silencio");
new Song("0Tt2ewjWMfKNWcwmOkMdXX", "Maldito duende", "Heroes Del Silencio");
new Song("3MxvNm02fkyrFDKPTh3ivi", "Lowline", "rei brown");
new Song("3cw9M0FrHA2cabBmhmxfxH", "Chaplan Candy", "rei brown");
new Song("27uyq0fEgkUnffxd5sNgeE", "You Lost Me There", "George Clanton");
new Song("1pwyi9Y9QE7M76fse2knBa", "Slide", "George Clanton");
new Song("7xWohUdw7Y55Pew3PbL2OV", "Blast Off", "George Clanton");
new Song("0Fj3mbyJXVXWGpi8bo2A2O", "Tie Me Down", "George Clanton");
new Song("4Kh8w1MgC7LYHSbSX2lDzP", "Make It Forever", "George Clanton");
new Song("0lrUh5vot66Srp1aeLTvej", "To Let A Good Thing Die", "Bruno Major");
new Song("1siqwUNydX8aQjUIVvJ6Pz", "I'll Sleep When I'm Older", "Bruno Major");
new Song("3eZS4TyX2KMvD621AD9MqY", "Figment Of My Mind", "Bruno Major");
new Song("2lU8zMzPhEEDuiUUcUIZAL", "Regent's Park", "Bruno Major");
new Song("5unXHHcSQLGO19RuVqZB6d", "The Most Beautiful Thing", "Bruno Major");
new Song("5PclVjs7jkiMV2oedFYmuO", "Old Soul", "Bruno Major");
new Song("2Nutj7BwscOhrjMSf7YHaJ", "Something Cosmic", "RIZ LA VIE");
new Song("0Pr2B3eAug5PK9mBf2OzvW", "She Said", "RIZ LA VIE");
new Song("13aDbIPxcbnDv3zGCDeqCb", "Nitetime In Atlanta", "RIZ LA VIE");
new Song("1jlO9wxjfdVFI4nnog8tVx", "My Old Friend", "Unique Salonga");
new Song("26JdDecoaQcOXHSohdtyss", "We Know", "Unique Salonga");
new Song("71fkgQ9m42g1OK9qtGiLxM", "Paalala:", "Unique Salonga");
new Song("24bmXekGRqVFRlPYdfzyJr", "Midnight Sky", "Unique Salonga");
new Song("7G4yV46j5P6Z6bCxoMzLIe", "Apoy Ng Kandila", "Unique Salonga");
new Song("2Qnrcw18yj7PDTCOoOyuCu", "I'll Break Your Little Heart", "Unique Salonga");
new Song("4chNJfH8mhYiLotDuDURkT", "Goodnight Prayer", "Unique Salonga");
new Song("20cUmJ3W1PLxbcXFbPGiHZ", "Jules", "Unique Salonga");
new Song("3jDDyw3l2KvSEaPdzkjCei", "OZONE (Itulak Ang Pinto)", "Unique Salonga");
new Song("0lCX1Ro9NHYdQ7GomO8FCd", "Cha-Ching!", "Unique Salonga");
new Song("0ptC1I5ZxJDm1cQ6SBqsDM", "Don't Worry", "11:11");
new Song("0KSjX6P9gbg6t3l1ZFSuDe", "Byo", "11:11");
new Song("15Hy4NsbvkcSygqXC2vZdL", "West Side", "11:11");
new Song("10wq6YHJt1IRPqEkTntFcu", "Calling", "Verzache");
new Song("3z6UUdNXqe6RgdCBlB0bn1", "Distant Restart", "Klaatu Suuns");
new Song("7MFvHO0ackOakz2zOWHUzS", "Brain Option", "Art Contest");
new Song("1IDeQGkKcWIydIETfGnNwi", "Not Just Dancing", "Art Contest");
new Song("5WZ9LaFihndn3ZmI887lqu", "Fiery Hand", "Art Contest");
new Song("07UjHiSAzFsXY1FpG7lErp", "Sun Halo", "Oberhofer");
new Song("1bRrJaO9IHxsx8OY3ly5di", "Púrpura", "Nanpa Básico");
new Song("6pwYbD6wkai6S3iquVyq47", "Niño Perdido", "Sonido Gallo Negro");
new Song("3usBViVaNvJsFkFxUpOxCP", "Never Break", "Langhorne Slim");
new Song("4WHmafrJ0ANeLFf7UlXjiM", "Messed Up", "Verzache");
new Song("3kJFOAzggfdQh8JmukWWq0", "Are You Coming with Me?", "Kai Straw");
new Song("77gQSJlncgT3HWmBfy9CQ9", "Aire", "Nicole Horts");
new Song("0GUF4GxxXQDuyLNp0Wqa1W", "Where I Left My Heart", "Silver Rose");
new Song("67u55G1oKniIsCBQoM43h1", "Spaghetti", "City of the Sun");
new Song("06yxqYBEv95RTvSTWUOOcm", "Crimen", "Silver Rose");
new Song("5Pd4DM7B4xm073ZK6840NU", "I'm Alright", "Silver Rose");
new Song("5tRFtEiBSsBBCPHdwkfGp1", "Noches", "Silver Rose");
new Song("0IHWITC8b1u4edMKWZaJ2K", "Sueños de Amor", "Silver Rose");
new Song("4M9gZEtOSf2I1hyGNvZbpF", "Take Me Home", "Silver Rose");
new Song("3M8FzayQWtkvOhqMn2V4T2", "Lean on Me", "Bill Withers");
new Song("6D43oUO6nImERk2psfXdNY", "Afterlife", "Arcade Fire");
new Song("4ld9QYEpwDD3m8gGfUn19Z", "Porno", "Arcade Fire");
new Song("0MWnFXte9zokisZDWZG0gR", "It’s Never Over (Hey Orpheus)", "Arcade Fire");
new Song("7zIgrNq7doluy1dMdTli3u", "Here Comes The Night Time II", "Arcade Fire");
new Song("53849j8C8EO07O1gCdzgTr", "Awful Sound (Oh Eurydice)", "Arcade Fire");
new Song("3KMhWFbexTo20tH3hwK61K", "Normal Person", "Arcade Fire");
new Song("4mzBH5tCKO6lHqRN3awTJC", "Here Comes The Night Time", "Arcade Fire");
new Song("25r99eqlm3lHGnZHoeg7YX", "Supersymmetry", "Arcade Fire");
new Song("3sa4mkNrXnhIsqDMuHx8ZX", "Besar en Luna Llena", "The Guadaloops");
new Song("1Eu8k38S6dFMuool5amlmR", "Wada Na Tod - From 'Dil Tujhko Diya'", "Lata Mangeshkar");
new Song("75jHGZkVYcbLDlS1SQkWgz", "way it goes", "Hippo Campus");
new Song("3sv9x84kPhVfHh1qpwa0Ks", "7/4 Shoreline", "Broken Social Scene");
new Song("3EjxAbEOH28icEK1ZFOUSh", "Essa Tal Liberdade", "Só Pra Contrariar");
new Song("1fkB6ypnGbxahR3bGij8xU", "And When I Die", "Mark Winkler");
new Song("63fj7dR4QGRHDHKZStUuAY", "Bad Things", "Milky Chance");
new Song("3bBbpnAT7JG0v2B2IkUppV", "Niña Surf", "Los Blenders");
new Song("1035DoHvpl9k0ExuDSRsSA", "Dead Cars", "Armand Hammer");
new Song("0PgU3qcRXrOKHkA1BMJNSj", "Half Man Half Shark", "King Krule");
new Song("1QMT8kb4hx6MZKIhUBoEtz", "The Cadet Leaps", "King Krule");
new Song("7dXyQvTkoiNVtsXAgFTXmL", "Bermondsey Bosom (Right)", "King Krule");
new Song("2LpcTDgPrMexPloLcHsSWl", "A Slide In (New Drugs)", "King Krule");
new Song("5v9GvZIJuD7QAkGIO8CHpm", "Vidual", "King Krule");
new Song("4Vkk3ZL9KHsiN4o7psSaRo", "Cadet Limbo", "King Krule");
new Song("38TrmGyKtQ4r9JxEfk8xlT", "Emergency Blimp", "King Krule");
new Song("4Hd4pcfUFQ5Czju0atfAKg", "Bermondsey Bosom (Left)", "King Krule");
new Song("6abKEw6Tgs54rQ0ZKiP0rp", "Slush Puppy", "King Krule");
new Song("5mWhSQfWEeBZD9YTd4yyFc", "Dum Surfer", "King Krule");
new Song("5cXVfj6h9ibAUm4vIN4nuX", "The Locomotive", "King Krule");
new Song("0GqkFzrmgujTMyGd01nCR5", "Biscuit Town", "King Krule");
new Song("6pwh8jxrpOoXAXhjAhIvFE", "Czech One", "King Krule");
new Song("6COk7pcDZmFBIfVy0K7GAB", "Lighten Up Kid", "Mayday Parade");
new Song("6hNMA0U2ZErKoLxD20iklY", "Anyway, Anywhere", "Klaatu Suuns");
new Song("2SzgK8i6si6ETtu57nTdSn", "Un Ratito Mas", "Bryant Myers");
new Song("7K2TlGoynaB74x1kwDx4hJ", "even If", "Lewis Watson");
new Song("1YlulsUKDduOmC7WxvXYPW", "Painkiller", "Ruel");
new Song("2dS0bHV8WAdL9t2Oy1RMV5", "Tripping", "Gorgeous Bully");
new Song("45IOlKX8MzjXibQP0ObDeG", "Patience", "Gorgeous Bully");
new Song("6N5DRCQUSXT1qQqmqsO92B", "Party All the Time", "Eddie Murphy");
new Song("1gTFwhHHsk4LwKGcLLe7r5", "Dmi Thing in Which New Information Is Introduced", "Jon Brion");
new Song("7b0NutXQ71gr9A8661Qc6d", "Groceries", "Kevin Penkin");
new Song("57t8BTQgH5qfHQXosfZ2pk", "Exploration", "Kevin Penkin");
new Song("37UNeKSzilH978feP03T04", "Reconcile", "Jon Brion");
new Song("6yzzno5cXBkh5c6UzRxcyM", "Lady Bird", "Jon Brion");
new Song("1Bv3h7Vc4AaYA2BcSM3rVd", "All I Wanted", "Paramore");
new Song("3P4Ng8mn5frgNJEAwKmsa5", "I Hope They Play This In Toronto", "Kai Straw");
new Song("5jSBnH9NyaNP5zdSB3pwgu", "Gimme Love", "Joji");
new Song("6Vgtvd7I5yopJdBuxqjBd2", "Your Man", "Joji");
new Song("3xo4Q43ei0ypZOvd2W1IqZ", "Like You Do", "Joji");
new Song("18CK4TdFJhPYQtUX2fq8D8", "Reanimator (feat. Yves Tumor)", "Joji");
new Song("7b2elHA9vOwpckUKm8SMyR", "777", "Joji");
new Song("6cbsrCcgGstNCgWFKnrQmc", "Mr. Hollywood", "Joji");
new Song("1ggYjU6zdFHgANcku82boU", "Afterthought", "Joji");
new Song("0QDBNUrc51sGxzmMTvH5kF", "Normal People (feat. rei brown)", "Joji");
new Song("3TVD4EADhgILXxFP4r1YFd", "Pretty Boy (feat. Lil Yachty)", "Joji");
new Song("2iES5ck2jsznpywJWMMzWR", "NITROUS", "Joji");
new Song("00l4b7ihmc0reIuQBSH9iB", "High Hopes (feat. Omar Apollo)", "Joji");
new Song("1zmgEIHE0eXH0IhBGuoTkP", "Run", "Joji");
new Song("5F1ZmucV0uJY14y2dYKePa", "Sanctuary", "Joji");
new Song("3rnRyo69s0yP795j9QAF2X", "Daylight", "Joji");
new Song("1FQpGAJiQgVd65IIBYkRVP", "Upgrade", "Joji");
new Song("2Imn5iTu2xD3gXCqpBqubu", "Tick Tock", "Joji");
new Song("5BibcbKVdZUuTttSG02JTp", "MODUS", "Joji");
new Song("3Nc86B5XmDlG1KuEeSLD8x", "Ew", "Joji");
new Song("6PQcT3UDWcO58RoEI33VpM", "Malcom Interlude", "Thelonious Martin");
new Song("4loXMor75kKVBB03ygwDlh", "Los Angeles", "The Midnight");
new Song("1TSMtCZksKCU9hXRy2V4K0", "WeMoveForward", "The Midnight");
new Song("6tJPdGKrbAeyhkkhn44RHR", "Days of Thunder", "The Midnight");
new Song("12OlfCFopRJpn0mKuIeIcz", "Kick Drums & Red Wine", "The Midnight");
new Song("2R3v2gnBITuIi5yfuEHMnQ", "Gloria", "The Midnight");
new Song("1SmwJJ8YVgiXtyE6elhUx1", "Tokai", "Taeko Onuki");
new Song("2lV8YY0GQYXgtUWXM4NJ4X", "4:00A.M.", "Taeko Onuki");
new Song("4iVMoqS3oOXSiEAx0l2BWj", "Back in Time (feat. Public Library Commute)", "Healy");
new Song("0HMjXBAZmSYOTTi33WpMso", "History", "One Direction");
new Song("4HbeGjbt7u3pvwDk1vN7P0", "Mystery of Love", "Sufjan Stevens");
new Song("5WfACgyEk4rwdWU3rrzNt1", "Godspeed", "James Blake");
new Song("0kc4G5tEdtmTB0w3gYmb01", "Desencuentro (feat. Soko)", "Residente");
new Song("10qaFO9To9Dkn8Qgw3B115", "No Te Importa Que Me Duela", "Lara Project");
new Song("263D4RdQH3bIwCCRbNrjzC", "Mercurio Retrógrado", "Lara Project");
new Song("5HMlQNbqL0TuIl8fGjBmYG", "Rottweiler", "IDLES");
new Song("1VZEFMJkZuppLl2PUsUkC1", "Television", "IDLES");
new Song("1aHlu4Hd1MkThwbgJtJOGD", "Love Song", "IDLES");
new Song("4VJI2lzbzxiWakC9P35TZP", "I'm Scum", "IDLES");
new Song("0gqsJm7b3KPSpqA2FsVn53", "Danny Nedelko", "IDLES");
new Song("4lD7gHKF1e8Y9stQuVezZB", "ghostin", "Ariana Grande");
new Song("4PpuZIMmeng6qPicveSI22", "Beso", "Jósean Log");
new Song("4miKDdaWW78mKwx6TIvOa0", "We Might Be Dead by Tomorrow", "Soko");
new Song("5lMJTWXtWXFqKpi1a0qna9", "A Word of Wisdom", "M83");
new Song("0yrPBI6TUysAU0OQbbd7IH", "Planeando El Tiempo", "Elsa y Elmar");
new Song("5EpLeWSwqOG0mZW0R4WdKQ", "海浪", "deca joins");
new Song("5gXFkeFEWQAIxzlTr9S8Jz", "Listen to Everyone", "Oberhofer");
new Song("3IZw9tALLeCAlCgaFES3U5", "What You Know", "Oberhofer");
new Song("7uzlKEe0bpDLC452SZqksW", "Me 4 Me", "Oberhofer");
new Song("0gn5HTzwrLAw3KLuodW5vo", "Ballroom Floor", "Oberhofer");
new Song("0YOIcJVtSwriTirH7cs92D", "Someone Take Me Home", "Oberhofer");
new Song("2OJT4eWx0JAANBffOWiv7T", "Together / Never", "Oberhofer");
new Song("754J2T5yFMo6V5cupl36Bb", "Memory Remains", "Oberhofer");
new Song("7g3PAro4AFinj1nFXLgLiD", "Chronovision", "Oberhofer");
new Song("4EqCc1MliPmnrXbcTBitFU", "Nevena", "Oberhofer");
new Song("24MWSatP5sTylISvJONhnB", "Falling For You with Justin Bieber", "Jaden");
new Song("4NU4ZK3ncM05KPUc8JSuQ5", "Circa 2015", "Jaden");
new Song("5HopPxueKZJfrvXYPfT42T", "LUCY!", "Jaden");
new Song("5JF353xKQVcUAhdzNAkg0n", "Everything", "Jaden");
new Song("0hmA5UgR7wphVWN83AVDgF", "Rainbow Bap", "Jaden");
new Song("5mjWvdjBNY5UMT0ndAbGPk", "Remember", "Antônio Carlos Jobim");
new Song("2hXBS8q9rGMovfG1S8FB4F", "Wave", "Antônio Carlos Jobim");
new Song("5jBv1j7ISp1ja8e1N2oSmt", "Para Machuchar Meu Coracao", "Stan Getz");
new Song("15ouqiBsgL12olEwP3COsH", "Águas De Março", "Elis Regina");
new Song("209ucYTS6vWEV5iydrHiOt", "Só Tinha De Ser Com Você", "Elis Regina");
new Song("28PORYgAQ5vrbwtobRlCoq", "A Felicidade", "Antônio Carlos Jobim");
new Song("17ryxPEatRV7KXunRoHSgE", "Louco", "João Gilberto");
new Song("3ycf2bdoyYW6KFX0PL9NDO", "Back In The Day", "Mac Miller");
new Song("75fDVecaFMegTxBhb4ceqL", "Ayye", "Mac Miller");
new Song("2LpcEVDlL4j6SDQqpKzopv", "Ven a Mí (feat. Caloncho)", "Leonel García");
new Song("3pe0I1lEtieR766wwjiypU", "Just A Little Bit Of Your Heart", "Ariana Grande");
new Song("15AbuFJdFrbINydSMSqVhV", "Aléjate de Mí", "Camila");
new Song("65bUBhjjibVJOuvPtbFF24", "The Years (Prologue)", "The Midnight");
new Song("7c1mJwugEp6fUU1GH4Vywi", "Baby Blue", "Tigers in the Sky");
new Song("2R7r52Ar8PrKCysGFUPynn", "Ojalá que te mueras", "Pesado");
new Song("1AMBOSeXi1bqHDTi8EeSR6", "It's Not You It's Me", "Coconut Records");
new Song("1IF5UcqRO42D12vYwceOY6", "From the Dining Table", "Harry Styles");
new Song("4Q66chx9WzqWcLItXoZ5r4", "Cherry Wine - Live", "Hozier");
new Song("3LueS3mbuB1yaJNN0Ale6U", "Avant Gardener", "Courtney Barnett");
new Song("1HyImWEaQ6ApypgRa7oBMX", "Sea of Dreams", "Oberhofer");
new Song("07ld47SfHdQXvsZpmWbalp", "Estrechez de corazón", "Los Prisioneros");
new Song("3VwZqgfrM3xb1usuLprkTu", "cellophane", "FKA twigs");
new Song("4lIKzEAa32N7cpLVLgGigS", "Back To You", "Coconut Records");
new Song("68eVFOxLTa0fYOAHhzITDN", "Prenda – versión acústica", "Alex Ferreira");
new Song("1BcneDitQuJHKkiwnRkT6x", "Let's Talk About Your Hair", "Have Mercy");
new Song("2y8Lwq5A5wuDDTbJprkkGM", "Hoy No Me Puedo Levantar", "Mecano");
new Song("4iqXKJhwbOtOT5aHZr7Fxj", "Me Cuesta Tanto Olvidarte", "Mecano");
new Song("6Vy53iriyX8Vqx0V68Jzn2", "Cómo Te Va Mi Amor", "Pandora");
new Song("1OB7cLxxCWA8gbbfjFNNej", "Hacer El Amor Con Otro", "Alejandra Guzman");
new Song("1YFBO31kSEYo1DVkjSj8LG", "Si tú no vuelves", "Miguel Bosé");
new Song("62clthR0fZmLbxeqxVJatQ", "Que Lloro", "Sin Bandera");
new Song("3M1H1CWjrSq7nxABHc8EXv", "Lobo-hombre en París", "La Unión");
new Song("0b53GyMOfBCt5L6bh0CH3f", "Las Mil Y Una Noches", "Flans");
new Song("62qI8m0sXpzlSjYYx0nZ83", "Si No Te Hubieras Ido", "Marco Antonio Solís");
new Song("14R3odsoHPOo95ffMG7ei1", "Call Me Joe", "Jukebox The Ghost");
new Song("7fIFq5maHJBEPay9eyQTkp", "Flower", "Johnny Stimson");
new Song("2NCFpevBcNb764LIvvNH8F", "艷紅 (Live)", "deca joins");
new Song("3YKY3TM1NIdY8GDmzPpLB4", "Sueños", "Alan Troy");
new Song("1uP8UVMXcTJn28TbhfR2Wo", "Paul", "Big Thief");
new Song("1RI9Qpt8QbYtwfCW8npcO1", "I Didn't Know", "Skinshape");
new Song("0pe4ZDlIQ3mo7pVJC4liAa", "Note", "Nat & Alex Wolff");
new Song("7rP2vMICDWDPFrSHbtC32U", "A Word of Wisdom", "M83");
new Song("1zvdOpnTT7U3IQXq6vJHvJ", "Is There a Place I Can Go", "Trudy and the Romance");
new Song("2dgFqt3w9xIQRjhPtwNk3D", "Death By A Thousand Cuts", "Taylor Swift");
new Song("6P7tTFzn6oNa0GL8w8oazE", "Make You Feel My Love", "Adele");
new Song("1dGr1c8CrMLDpV6mPbImSI", "Lover", "Taylor Swift");
new Song("2IbQBVzWkT4CF9aEUWek2o", "The Wave", "Colouring");
new Song("50Sjt1wULRlqtfSSDidqXT", "Mind Gap", "Point Decster");
new Song("6NB1KNeHmUmH8WIUpoYpIq", "Corre", "60 Tigres");
new Song("6Lmw9XlDKK5qvVQ2qk0mDk", "Valiente", "Mi Sobrino Memo");
new Song("02P3oPhKA2SAlLlFvTvEgg", "Entre Paraísos", "Arial");
new Song("4vjGixzehfm6Cu9E9YpOlm", "North", "Rosetta");
new Song("32XZC3nzNEmvndLxNcO4L1", "West", "Rosetta");
new Song("2KSIpdpubDhmkISGnPAcTj", "Ahora Te Puedes Marchar", "Luis Miguel");
new Song("2Luer8kLzFkQcjw8CU8x35", "Cuando Calienta El Sol", "Luis Miguel");
new Song("3gqgSM82j6NMAj4Jllr06T", "Vete Ya", "Valentín Elizalde");
new Song("2hrzkF8lwfufynP0lE1uqv", "La Chica Del Bikini Azul", "Luis Miguel");
new Song("309MON2vaIXlLuUkTsRPWc", "No Me Puedes Dejar Asi", "Luis Miguel");
new Song("1uKjQoh8JZj9ryuYRhpd7E", "Ahora Te Puedes Marchar", "Luis Miguel");
new Song("21Ullb4TU8qMsQd0Iselng", "Sabes Una Cosa", "Luis Miguel");
new Song("27XboT5Wb8VOn7A0heo3Ei", "Tengo Todo Excepto a Ti", "Luis Miguel");
new Song("7BwxbmYFy0l3ROHDjV2c14", "Culpable O No - Miénteme Como Siempre", "Luis Miguel");
new Song("6F9yAYUaNbUhdlQyt5uZ3b", "La Incondicional", "Luis Miguel");
new Song("5r29thLDdj6dkXbqK8XVbW", "Terror", "El Mató a un Policía Motorizado");
new Song("3MJEeIswqie3xdWT8TFY80", "Meteoro 2028", "Los Natas");
new Song("7wKEBslPrHvbP2iL4z8cG2", "Carl Sagan", "Los Natas");
new Song("6s9HUUwQLIIwv3PaB28k5U", "Brisa del Desierto", "Los Natas");
new Song("61oZerVAQBKxRUPpOmkQIG", "South", "Rosetta");
new Song("6s1QAIr9vmYiEelpl5lFew", "East", "Rosetta");
new Song("4dtQcMVCaXqlKDmJZPQ1x0", "Electric Tears", "Buckethead");
new Song("6wbMtIVAux339lmOWlKZIx", "Gifts for the Earth", "Deafheaven");
new Song("5IlMoKCS8xZYRa67336c5g", "Come Back", "Deafheaven");
new Song("5mFZdkeQqQiXDceXuqxlwE", "Baby Blue", "Deafheaven");
new Song("05xdNxzC7gXOx9UlRHvH1v", "Luna", "Deafheaven");
new Song("0ZA9Zg4umQEzdB3Fv8qr4E", "Brought to the Water", "Deafheaven");
new Song("0FlfN5cbUUpIHCRH8X1M44", "The Climb Back", "J. Cole");
new Song("1K8MgzVyx6MMo8Y0rfDx1O", "living single", "JPEGMAFIA");
new Song("4IFhvWVK6v1oPjNWULLyKH", "My Soul Is Lemonade", "Kai Straw");
new Song("3qxbhEYg8QgcVy9Dkk7r5R", "No Words", "Clan of Xymox");
new Song("1bWEngw5tAF7vWByrf5Oy5", "bloody valentine", "Machine Gun Kelly");
new Song("2RlgNHKcydI9sayD2Df2xp", "Mr. Blue Sky", "Electric Light Orchestra");
new Song("4fAeGE0dckcs5YMmA9Gb58", "Mérida", "Diamante Eléctrico");
new Song("4dI0gr2tJqit5gg69AJvTK", "Oro", "Diamante Eléctrico");
new Song("3Q30YDVUjGuHMe1MZs1Xl5", "Nefertiti", "Diamante Eléctrico");
new Song("7gx8zoP2ClQcMXFD7KFYD1", "Solo Tú, Dueles", "Diamante Eléctrico");
new Song("4iPQDiBXh6oG6Q3baFOSls", "Maneater", "Grace Mitchell");
new Song("1meVuY0rHlRL4o2Q5uGqUd", "#9 Dream", "José González");
new Song("6gREYnl1rgTBE06YIDZheT", "Don't You Want Me", "Bahamas");
new Song("3NsyRkNYWUz5pIvoBoSGKf", "The Wolves & The Ravens", "Rogue Valley");
new Song("3dnswoe0E6Rf1vKdKzNdKs", "Escape (The Pina Colada Song)", "Jack Johnson");
new Song("4Gbz1YBij1vdogaY9FyayG", "Lake Michigan", "Rogue Wave");
new Song("5HV47k4eFD8dCqixc6xZRz", "Don't Let It Pass", "Junip");
new Song("1kNSycnXv10UpYbCXIgZYo", "Stay Alive", "José González");
new Song("1v0JeWn88JGmETJGVKVpcY", "Dirty Paws", "Of Monsters and Men");
new Song("6ujI5tE2O7PIBtG7A7ZdQN", "Step Out", "José González");
new Song("6bOkaEXc5CopinGazSLokx", "WHAT'S GOOD", "Tyler, The Creator");
new Song("51RN0kzWd7xeR4th5HsEtW", "IGOR'S THEME", "Tyler, The Creator");
new Song("7vmai31HHPvZbl3taI9arm", "Pero Qué Necesidad", "Juan Gabriel");
new Song("0asofNroI81kCUKWCRqvnC", "Yo, Robot", "Sunshine Pink");
new Song("6uyWYFp2UtKvaUdjWBqYc8", "Pt. 2: Extraño a Mis Compas", "Sunshine Pink");
new Song("4U0qLHLakxW5lK0w1h37Nj", "El Topo", "Sunshine Pink");
new Song("5wlz2r9Fu9kL9Snt4lntul", "Poppy", "Mac Miller");
new Song("2TyjVO7KBdGHBvQxAnFFsa", "Kool Aid & Frozen Pizza", "Mac Miller");
new Song("0DCu6lwtdiVjMixpQJcGG3", "Knock Knock", "Mac Miller");
new Song("51pshtuYkgUQnt5huMPbKL", "The Spins", "Mac Miller");
new Song("6vVftwBiIaM9xDVZhSwTCJ", "Senior Skip Day", "Mac Miller");
new Song("0vcn2LXvKArk9d9OIwO9Ai", "Kickin' Incredibly Dope Shit (Intro)", "Mac Miller");
new Song("29GefKRTSVW3ag4Xegm8jP", "Nikes On My Feet", "Mac Miller");
new Song("7HyEVTcgQdkHGEvR565bTt", "You", "Yellow Days");
new Song("5vVOWIu7nrYaYHWNatg1fr", "Purchase Price", "Paul Mccall");
new Song("7gKK7lF3DtzdXP7dC6ntZU", "ROUGH 7", "JPEGMAFIA");
new Song("59ltXimVw3hLeqWXKlZs03", "Una Casa", "Sabino");
new Song("4P04T22VRDMfG7Yk0SMMxP", "Cabin Fever", "Jaden");
new Song("2UajPRSnGWNtqXHBRa0HAD", "Second Wind", "Healy");
new Song("0FB9CE48Y8yw0mxdzmwpeb", "Closer", "Nuages");
new Song("0UqwIL59AsdSTdmewiWXvj", "Tic", "No Buses");
new Song("2ov7jzg8iAWWlpZuaXPUBK", "Dormir Sin Coger", "Arroba Nat");
new Song("2LXtYN1okFrtAvhCRGYAtp", "New York Kiss", "Spoon");
new Song("1SSKN5iSQ8ImhXaiSWlHD3", "Let Me Be Mine", "Spoon");
new Song("1rX21zAT49jF2hbjDSuccp", "I Just Don't Understand", "Spoon");
new Song("1MLlsxqjv0mJKdWMmK3MOU", "Outlier", "Spoon");
new Song("2ByepaHHF6OCV9pZpLIMtr", "They Want My Soul", "Spoon");
new Song("0r37xO7gfeJfc2LCn3Po6t", "Do You", "Spoon");
new Song("68foXzhSgAKKiWqOE1eJco", "Knock Knock Knock", "Spoon");
new Song("2CfrVHG9aS3HWaVLZk8wZf", "Rainy Taxi", "Spoon");
new Song("0H46xH5c7p5K09Vt5gX3Ny", "Rent I Pay", "Spoon");
new Song("1aXtZAX0DubViRjIDvvKOM", "Total Praise", "Sunday Service Choir");
new Song("5s5URjHYRVt5oyp2gdlB7h", "Satan, We’re Gonna Tear Your Kingdom Down", "Sunday Service Choir");
new Song("5p4aqYZlL44hI0imyk7AV2", "Paradise", "Sunday Service Choir");
new Song("135gooUtfMruH8HFrRqhvn", "Sweet Grace", "Sunday Service Choir");
new Song("6jCQxiqyxFKM3euH8X526R", "Back to Life", "Sunday Service Choir");
new Song("3RGLwFXRrRAyTQtIxNc3cQ", "Souls Anchored", "Sunday Service Choir");
new Song("35A5y8tHvRrLOleQDsNu76", "Sunshine", "Sunday Service Choir");
new Song("7b0WhXsRuS4aJFwOI5WUFc", "That's How The Good Lord Works", "Sunday Service Choir");
new Song("77Ozvyd5Hb2JelgPAefv5I", "Weak", "Sunday Service Choir");
new Song("2vUNNg9K4PAY5o3OBwGUVU", "More Than Anything", "Sunday Service Choir");
new Song("5anPHKl01TNpTe618GzX1m", "Ultralight Beam", "Sunday Service Choir");
new Song("60YO6vmmFsIPIhxvLTmwhL", "Lift Up Your Voices", "Sunday Service Choir");
new Song("6lfCkiP0h3KyWa7BQNoOu9", "Follow Me - Faith", "Sunday Service Choir");
new Song("2tLH5EsewbZNvmWidJqzDF", "Father Stretch", "Sunday Service Choir");
new Song("3LCvxWsmC6UVTWpynIYFWo", "Balm In Gilead", "Sunday Service Choir");
new Song("0kjm5DAzDidQhHgElDrdfq", "Rain", "Sunday Service Choir");
new Song("4pSUxkUKeWFyFNkzl7XoBU", "Revelations 19:1", "Sunday Service Choir");
new Song("077yGhj0JCilTx1aNgoAE8", "Excellent", "Sunday Service Choir");
new Song("5y8apzJP1xF42QHMjSauvN", "Count Your Blessings", "Sunday Service Choir");
new Song("2rbuUlu9AsqqfLlxS2fib8", "Polar", "NORTE");
new Song("6W4no5exe0B9TwGRhn98xr", "Petricor", "NORTE");
new Song("62FHlCqoihuvRCRQ9cWlTA", "Luces", "NORTE");
new Song("5jrTiIhaP25UPGo54V5HL6", "No Hay Futuro", "NORTE");
new Song("0znhPiQvvLfOxDB0cJWu6z", "Pasado / Presente", "NORTE");
new Song("4waqcUQWdj0yH26STWl2Rq", "Rosas", "La Oreja de Van Gogh");
new Song("22seP38foydqUMp5Fvkcjm", "Inolvidable", "Reik");
new Song("4iuQ88fgaqBRkzb1JWKUbZ", "Desde Que Llegaste", "Reyli Barba");
new Song("7MbT4I8qGntX4fMdqMQgke", "peace", "Taylor Swift");
new Song("6MWoRt97mnSTXZhu3ggi9C", "hoax", "Taylor Swift");
new Song("5kI4eCXXzyuIUXjQra0Cxi", "betty", "Taylor Swift");
new Song("08fa9LFcFBTcilB3iq2e2A", "epiphany", "Taylor Swift");
new Song("6VsvKPJ4xjVNKpI8VVZ3SV", "invisible string", "Taylor Swift");
new Song("7kt9e9LFSpN1zQtYEl19o1", "this is me trying", "Taylor Swift");
new Song("6KJqZcs9XDgVck7Lg9QOTC", "seven", "Taylor Swift");
new Song("0ZNU020wNYvgW84iljPkPP", "mirrorball", "Taylor Swift");
new Song("1MgV7FIyNxIG7WzMRJV5HC", "my tears ricochet", "Taylor Swift");
new Song("4pvb0WLRcMtbPGmtejJJ6y", "exile (feat. Bon Iver)", "Taylor Swift");
new Song("2Eeur20xVqfUoM3Q7EFPFt", "the last great american dynasty", "Taylor Swift");
new Song("4R2kfaDFhslZEMJqAFNpdd", "cardigan", "Taylor Swift");
new Song("0Jlcvv8IykzHaSmj49uNW8", "the 1", "Taylor Swift");
new Song("7mM6BIdq101IEn4hxAVqo2", "Destruccion", "El Mató a un Policía Motorizado");
new Song("5iQfFljjs2rwXYe68V9VyE", "Ahora Imagino Cosas", "El Mató a un Policía Motorizado");
new Song("4w9TBRGhvbhiLQB8jVCusl", "Cheetah Tongue", "The Wombats");
new Song("1wq5gRZ5JRn25N4JCUg1oO", "Storm Before The Calm", "Tom Misch");
new Song("7qGAPavRijMOtbm7EzCaUq", "Julie Mangos", "Tom Misch");
new Song("39WFZVKifA8Fl2TZI2kp0S", "Last 100", "Tom Misch");
new Song("1vzqTU4KJrKhezhPgZkjTr", "Kyiv", "Tom Misch");
new Song("4xWLo3R0jjTVOdmtjC5MKI", "I Did It For You", "Tom Misch");
new Song("6yvTddeHmEiYG7FN8a5frz", "Lift Off", "Tom Misch");
new Song("28wERzXJWMb4Qx1bf9EXyW", "The Real", "Tom Misch");
new Song("5oEhWt6RfUHSBiSfZVnymh", "Sensational", "Tom Misch");
new Song("5TgZ7lOUugOdabBcD9a6ud", "Nightrider", "Tom Misch");
new Song("4Goj7amQLl2PiPYaiB0VlV", "Tidal Wave", "Tom Misch");
new Song("0E6jX8jTWevqFpJ2u7dXrh", "Manuel el Brujo", "Dolores De Huevos");
new Song("5aCOgoyVrIYxB7rScX1vJG", "La Naturaleza Incoherente del Ser", "Dolores De Huevos");
new Song("7AfwjD3R1XfzMTiSi8mjgQ", "El Miserable", "Dolores De Huevos");
new Song("79l5GDlwFiFr0ey2Dd55Cj", "Poesía al Sol", "Dolores De Huevos");
new Song("2Z4RTX0M0EuyW4TtpMyC1Y", "Maltrato Animal", "Dolores De Huevos");
new Song("2rPqOsd6iHHsm2MYilfOA8", "Caballete de Arrugas Aprendiendo", "Dolores De Huevos");
new Song("0b6pOPtpFt3KUSWm35b9lP", "Por las Orejas de la Reina", "Dolores De Huevos");
new Song("2e2sjg5Na8ATIgwb1T7zWJ", "Weather", "Ginger Root");
new Song("3zy0RvRbURGe1WCDNlE3Mk", "Tristan & Isolde: Vorspiel und Reigen", "Richard Wagner");
new Song("1ATUgQ62kzOcLJnJgVSaYm", "Tristan & Isolde: Isoldes Liebesverlangen", "Richard Wagner");
new Song("6ga05d78sLULdD5BatI1XM", "Tristan & Isolde: Nachtgesang", "Richard Wagner");
new Song("5henfh7Xi8QxYe9F5ggIN6", "Tristan & Isolde: Einleitung", "Richard Wagner");
new Song("3eddddUsVZSYgk9Vs9a4L5", "Tristan & Isolde: Isoldes Liebestod", "Richard Wagner");
new Song("6hABrbNtm1EgnFPQ1qTH8C", "Turandot / Act 3: 'Diecimile anni al nostro Imperatore...Padre augusto'", "Giacomo Puccini");
new Song("70RecAVg5QudOXfJs64sM5", "Planetarium", "Justin Hurwitz");
new Song("0CP1PvoR5Z7vpAb84nzGqZ", "Gray Romance", "The Shivers");
new Song("3uYrVtgRuz4XiOOXDV805X", "Dreams", "Nuages");
new Song("3szUadejZOGpLb3FMdVPsf", "I Don't Believe It", "A Beacon School");
new Song("47w6S27JF4Zvrz1Wd6R66Z", "What Kinda Music", "Tom Misch");
new Song("2lXFtsU8naRn2mC0DACJEl", "Festival", "Tom Misch");
new Song("5mlwzDt1XtsWfLVHO5vSBm", "Jakob", "La Buena Banda Isabel");
new Song("1KIFzfieBfkpYL90sLJ3D6", "Real Love", "Sugar Pine 7");
new Song("2u42cxAUjwl6tEew4HZQyh", "Ortega Y Gases", "Divididos");
new Song("1ZeOWborq2UNoX9ZiiKeNH", "Pan de Mesquite", "Biomigrant");
new Song("2USTVgd20XRLMAhiYNklN8", "Livin' Loose", "George Clanton");
new Song("5rfbqI2j7IN7oNx6LSq7pN", "Roma (LRDP Maqueta)", "Sabino");
new Song("0h4kOUA5ec7k7oW8pEeYnC", "Lonely Lullabies", "Kweku Collins");
new Song("0oH6dm5Mc0zzUfe8NERSvL", "Breathe Life", "Jack Garratt");
new Song("6V2QgOIMT94HhsfeIVbbZm", "Manila", "Maribou State");
new Song("0khJmjhaoYJ0KsVDmOqXZb", "Minimal", "Bo Ningen");
new Song("4e57YPpyBpWetYWk2weJt4", "Lluvia", "Loiis");
new Song("76NtMPMpA6fuUH4euMYZoD", "Buenos Genes", "Rels B");
new Song("7ayuuCBLywECYE5cfv9gXy", "We Will Be Alright", "Two Feet");
new Song("0EIxLAgV5FNxKQiqI4n923", "Pink Reprise", "Two Feet");
new Song("1Mp76fZm633qPZftr4MXa3", "I Can't Relate", "Two Feet");
new Song("04c6EIcUvkRv3xWrBol3J1", "Felt like playing guitar and not singing part 2", "Two Feet");
new Song("02IzyNFIbOqr7HruSSPXuI", "Maria", "Two Feet");
new Song("14CF8uYWS5hV0Qvy5GAFqU", "Grey", "Two Feet");
new Song("7cS8eqcw4EQraaGYcUAANo", "Lost The Game", "Two Feet");
new Song("67JgbuqPg9YC1RfahNnr7j", "44 Lies", "Two Feet");
new Song("7aW115ZGsZcA0Y2HQxiUIU", "You?", "Two Feet");
new Song("29Q7B99CvWw145Eq4nAB5D", "Call Me, I Still Love You", "Two Feet");
new Song("5nj7iytZfhPMn7hZ1Kzn00", "BBY", "Two Feet");
new Song("4IHiN5A0ythEPmWIKSc7gc", "Pink", "Two Feet");
new Song("2vPxgazztrgi8ZYdc9REl0", "Intro", "Two Feet");
new Song("6ZmzcxO4QxkjwbjBp83gSa", "Paradise", "The Moving Pictures");
new Song("56wQddZqh3S2y2TGhgEyQw", "Mine Will Always Be Yours", "The Moving Pictures");
new Song("0mKsQTAdhUeqLxhPQr5dWB", "5am", "The Moving Pictures");
new Song("2GfEsCerbcBmFCYiy4Fw2R", "Traditional", "The Moving Pictures");
new Song("4ccM73nP37VXgxwWei58BI", "What Do Ya Say?", "The Moving Pictures");
new Song("3nOB6M08yvPuhRyzodYVHp", "Penelope", "Andrew McMahon in the Wilderness");
new Song("7cA1ZJPmiLU1rAtGZIUvJF", "Paper Rain", "Andrew McMahon in the Wilderness");
new Song("0uZc2eGEpuQi1qbaqcFOk3", "AtorihS LE", "El Shirota");
new Song("62hTXlVQacy3pjBW4ntRPl", "1000 Doves", "Lady Gaga");
new Song("6kXRZSe28BawCiEdME8YLk", "Chromatica III", "Lady Gaga");
new Song("7sKbyYeJnITO1Eh9xd0lKd", "Replay", "Lady Gaga");
new Song("7JDbfYUHjDzQPFSDh5lzGs", "Enigma", "Lady Gaga");
new Song("1IWNylpZ477gIVUDpJL66u", "Sour Candy (with BLACKPINK)", "Lady Gaga");
new Song("3CidPLqWXqgesJlwYVJZdy", "Plastic Doll", "Lady Gaga");
new Song("6qI0MU175Dk2DeoUjlrOpy", "911", "Lady Gaga");
new Song("0oQc0F6KUE7QY7k5TU6bic", "Chromatica II", "Lady Gaga");
new Song("6hyQVqfHFvsJDjcmj4qrHf", "Fun Tonight", "Lady Gaga");
new Song("7ju97lgwC2rKQ6wwsf9no9", "Rain On Me (with Ariana Grande)", "Lady Gaga");
new Song("4L6ihclQPu1hqP9r3WNJjQ", "Free Woman", "Lady Gaga");
new Song("7yBbV2k2S2uhaQc24NF2xt", "Stupid Love", "Lady Gaga");
new Song("41A89rj3GoMG6ktN37L7PG", "Alice", "Lady Gaga");
new Song("3CGZ7wfk4skmuyQgua1C1K", "Chromatica I", "Lady Gaga");
new Song("07zYusRvYr8nAZOBDguzWv", "All Glass", "Freddie Gibbs");
new Song("1DA6UYm3jqf8b3ecWUbo6i", "Skinny Suge", "Freddie Gibbs");
new Song("3RyLrayd9un9ClTah57JI0", "Babies & Fools (feat. Conway the Machine)", "Freddie Gibbs");
new Song("4mL25h2hl6gdyu9tNTudnI", "Baby $hit", "Freddie Gibbs");
new Song("2pFC6DEdMhxQWUTptwVyS4", "Frank Lucas (feat. Benny the Butcher)", "Freddie Gibbs");
new Song("5OkYfk72CNL8XLqa3gp9q7", "Something to Rap About (feat. Tyler, The Creator)", "Freddie Gibbs");
new Song("15NQ3x1f2GUhqs8oBXhTqp", "Scottie Beam", "Freddie Gibbs");
new Song("6kK3m2FiYERYrUF269y0Es", "Look At Me", "Freddie Gibbs");
new Song("1p1b9LdLJ0REuFJX9mYtFX", "1985", "Freddie Gibbs");
new Song("5V9lnDn1hePoudMfKfCTNl", "God Is Perfect", "Freddie Gibbs");
new Song("1W20XvsWK2hpdd7OWTMxXV", "the ground below", "Run The Jewels");
new Song("7AwycHHN62QYHPC7gkxMoH", "pulling the pin (feat. Mavis Staples & Josh Homme)", "Run The Jewels");
new Song("0g6CU8w2l4cOSoMxWyYDCT", "a few words for the firing squad (radiation)", "Run The Jewels");
new Song("7G3dhGDXbwSau6uEVJZDks", "walking in the snow", "Run The Jewels");
new Song("5inmVZriTY8jQDjeUXz05a", "never look back", "Run The Jewels");
new Song("6A0oV3M3A5MEfiTgNQRS6d", "goonies vs. E.T.", "Run The Jewels");
new Song("3NJoIm6cMclWtt7MJ3Xn13", "holy calamafuck", "Run The Jewels");
new Song("0z2NePAZsilxxeyropQU1n", "out of sight (feat. 2 Chainz)", "Run The Jewels");
new Song("0mMeKoNrRQaFq8zaO6tLnI", "ooh la la (feat. Greg Nice & DJ Premier)", "Run The Jewels");
new Song("5qKtAVqo3oePD69E5krICr", "yankee and the brave (ep. 4)", "Run The Jewels");
new Song("0ZOM6JG2OuaJF9VOSN6aCy", "Hidden Jewels", "Lonthedon");
new Song("4DXkg0aahmbBuTdINKZugg", "Hoy", "Residente");
new Song("5Yjn9kt00mOHg8CfNqMNmc", "Familiar Five", "Marcus Marr");
new Song("3gfs1GdabMnU45G2pKkMsA", "Lejos", "Rubytates");
new Song("3XetDJxSDARsex7zU9KEpM", "FANTAZIA", "Roy Blair");
new Song("6Hw21Z5CmEV78jrncFpMwz", "Tak Tiki Tak", "Harry Nach");
new Song("2N5zMZX7YeL1tico8oQxa9", "Crazy", "Gnarls Barkley");
new Song("0FMjqbY3aWo1QDbo3GwXib", "Always in My Head", "Coldplay");
new Song("4tjiivmWTWMLeFiLDuQpdG", "Girl", "Donna Missal");
new Song("5MChi9fdCbTIWDJPPUuuW6", "Beautiful Escape", "Tom Misch");
new Song("0qpSvzE0Rws3gVZNZCf04v", "XNXX", "Joji");
new Song("6RZqf37lR2vnJ2AiZFINtl", "Utah", "Brotherkenzie");
new Song("5jtbhF7zGZR4YRMxhLV4V8", "Perfectly Out Of Place", "Dreams We've Had");
new Song("6Ha8pqxdSJHdPY4tlzPhlT", "Hurry Home (with beabadoobee & Jay Som)", "No Rome");
new Song("0blDgW9NoPD52aPw8vUU42", "Ohmygodiloveyoupleasedontleaveme", "Clever Girl");
new Song("1xiDRipOEZGXW5CsqdIfx6", "April", "Kanazu Tomoyuki");
new Song("4vtiD6QnHMc5CMPZxUfojr", "Oranges", "American Pleasure Club");
new Song("1jecO8NeYLsVWVptITz4c1", "Tú", "maye");
new Song("0mfw7WbyFKZHKgxW6jpEuK", "Rom-Com Gone Wrong", "Matt Maltese");
new Song("2GHLPezLTERgiqCpFeR7PZ", "ほんをよむ", "百景");
new Song("3pSaXsCpRpYwzmdfoZ8ncV", "Less Unsettled", "Hemlock Ernst");
new Song("3vMb4PJslZDQMvsJ71AAmG", "Pickpocket", "Vanillaroma");
new Song("517sX57TlnUy19bkOBfnZS", "(forever?????????)", "glass beach");
new Song("2o86inEwGVf0dyn7EE7pDz", "Pinpoint", "Hayfitz");
new Song("1VUJHMFmkaHrGngkhObeo1", "Border (CH. III)", "Lewis Del Mar");
new Song("7egu63DOhNpivWOpGtzqGS", "Lamb's Wool", "Foster The People");
new Song("5UuBKEh3DansLsajRTTfAT", "Solar Gap", "Hinds");
new Song("4SBOc5H03M2AGbvb2J0zHh", "Town Boyz", "Ralphie Choo");
new Song("7huvZiaIjvIeyj9eOiHMho", "Cari", "Ralphie Choo");
