class Song {
    constructor(uri, name, artist) {
        new RandomObject("song", name, artist, "", "https://open.spotify.com/embed/track/" + uri, "spotify:track:" + uri + ":play");
    }
}

new Song("3ClBKQkKoaUQ6UOhe2xlJK", "Good News", "Mac Miller");
new Song("1LD52Nzt9wg1vB3F6gelPH", "Undo", "The 1975");
new Song("6QbI1KSaDQhftv6aGHT5vn", "Bodys", "Car Seat Headrest");
new Song("165cwz4wGlGz0uDBhxdKLY", "Right", "Mac Miller");
new Song("1SpJusI8TUxRQboKRdi16s", "I Want the Night to Stay", "Matt Duncan");
new Song("6QgPfp0ARMLlie81jVfsUb", "Give Me My Month", "James Blake");
new Song("0x2VgHoxUxKFbIUqQur8Fe", "Sino", "Unique Salonga");
new Song("4jXl6VtkFFKIt3ycUQc5LT", "Circles", "Mac Miller");
new Song("2HngDESphICt87xLY9LRnA", "1000 Boys", "Matt Duncan");
new Song("62FHlCqoihuvRCRQ9cWlTA", "Luces", "NORTE");
new Song("5EpLeWSwqOG0mZW0R4WdKQ", "海浪", "deca joins");
new Song("3WfSNAoj2D8C9noPSGZZFM", "Complicated", "Mac Miller");
new Song("397rM4wePe8bPJSMAwFNUO", "Good Times", "Matt Duncan");
new Song("4LX270g9HEBkA0qYtGAel8", "Los Bajos Fondos", "No Somos Marineros");
new Song("1HyImWEaQ6ApypgRa7oBMX", "Sea of Dreams", "Oberhofer");
new Song("2hwOoMtWPtTSSn6WHV7Vp5", "Blue World", "Mac Miller");
new Song("6lv5xJNWI2fYwjrPG4KFSe", "Beacon", "Matt Duncan");
new Song("51R5mPcJjOnfv9lKY1u5sW", "Never Meant", "American Football");
new Song("3Gda1sTo2ZjbztjjsnAsP3", "Slip Away", "Perfume Genius");
new Song("7BCzMKLKQwVSLtZcDGJTJt", "Floating", "Mac Miller");
new Song("1z3pPyR0cbquVYWZOHkox9", "Meanstreak", "Matt Duncan");
new Song("6pwh8jxrpOoXAXhjAhIvFE", "Czech One", "King Krule");
new Song("74WjYdm3Lvbwnds4thYPUU", "Turandot / Act 3: 'Nessun dorma!'", "Giacomo Puccini");
new Song("16umSNZfofRpDqTvf8DIAo", "Wings", "Mac Miller");
new Song("1IF5UcqRO42D12vYwceOY6", "From the Dining Table", "Harry Styles");
new Song("75GwJi8ruSsNTBLoGBMFBm", "drift/(:(", "Alek Olsen");
new Song("6DFpH1EwJp05AGgqX5OWZO", "Puritan Heart", "Matt Duncan");
new Song("1OuN92HcVG6NVpWbeESNB3", "Everybody", "Mac Miller");
new Song("65II7NFnz2mjfaCEKeJEux", "Enemy", "Kai Straw");
new Song("2hfoyc7ve6xM4ZEiNIiU1B", "Gimme Love", "Joji");
new Song("4U09Dsa20zQ5ducUTJEmB8", "La Asimetría Según Cardin", "Tino El Pingüino");
new Song("3Qa944OTMZkg8DHjET8JQv", "Woods", "Mac Miller");
new Song("3iRiQJsQmH0yPIOJn3Y4WQ", "Heart & Arrow", "Matt Duncan");
new Song("61HBuVsspScrGUobbfmhOT", "The Summer Ends", "American Football");
new Song("1ZMiCix7XSAbfAJlEZWMCp", "Falling", "Harry Styles");
new Song("2Yv2mHzr5AQavVdwQjEokV", "Hand Me Downs", "Mac Miller");
new Song("2IbQBVzWkT4CF9aEUWek2o", "The Wave", "Colouring");
new Song("166T5iL97Xaxb35mCV6abl", "Cuando Piensas en Mí", "Tino El Pingüino");
new Song("4ue1k6IIQFd0BAAiOF50yi", "Honestly?", "American Football");
new Song("3R8CyhJfVjvgIROd5RSGhQ", "I Can See", "Mac Miller");
new Song("3FlIxaICsgxU2lQg029fKp", "I Wanna Leave America", "Illiterate Light");
new Song("0G0NKx220sZpjXC4LSoCkA", "Honeycomb", "Deafheaven");
new Song("45b0d0jbSIyzZbZSYsJw1Q", "Butternut", "Healy");
new Song("0udOCZp7yk0Ml92C0k8H8D", "That's On Me", "Mac Miller");
new Song("0RDly6TkvnlYu26RuBw0Ym", "Soy vírgen y soy leal", "Julieta Venegas");
new Song("69wePb2qJWL7zgGRmge2Um", "Wall Ball", "Art Contest");
new Song("5gPXLYNb9XRFHgRfcUKiHA", "Cine Permanencia Voluntaria", "Little Jesus");
new Song("6CrnvqCxBKVWahSiQwOesM", "Hands", "Mac Miller");
new Song("7tIFZKrcPgzNUKBEU3Dvkc", "Mi Chica", "Los Reyes del Falsete");
new Song("7BJny7nQN5bY4EeGVU3kj6", "Head in the Ceiling Fan", "Title Fight");
new Song("6HYm04mKq02OtLMf6sGEFR", "Caruso", "Lucio Dalla");
new Song("1kwnxJNVl7cwcU98RvMBaR", "Surf", "Mac Miller");
new Song("5lMJTWXtWXFqKpi1a0qna9", "A Word of Wisdom", "M83");
new Song("1c7LdDERW45Sn0zzxFzH5E", "Chico", "Art Contest");
new Song("0pe4ZDlIQ3mo7pVJC4liAa", "Note", "Nat & Alex Wolff");
new Song("26G5nmIx7Yvq79bIIluyZV", "Once A Day", "Mac Miller");
new Song("1THOENDCBvX13qNkwctXlW", "Ghosts", "Mayday Parade");
new Song("48O0GrGJWml3DzHhC5sJ7a", "Karma Chameleon", "Culture Club");
new Song("3VwZqgfrM3xb1usuLprkTu", "cellophane", "FKA twigs");
new Song("6dFn6my1sHK2bcf23GlHwM", "2009", "Mac Miller");
new Song("67vV72Oo7aty9EqYj1mwlR", "Perfecto Miserable", "King Krule");
new Song("6zqK3fE8uCRLpZLUj9VGci", "Peer Pressure - From 'Eternal Sunshine of the Spotless Mind'/Score", "Jon Brion");
new Song("7doSYW71rxRVAj49ilysHd", "Our Love Remains", "rei brown");
new Song("01z2fBGB8Hl3Jd3zXe4IXR", "Come Back to Earth", "Mac Miller");
new Song("1yJZwBqTyGTB7mz8nZyiel", "Barcelona", "George Ezra");
new Song("6VzcQuzTNTMFnJ6rBSaLH9", "Fine Line", "Harry Styles");
new Song("7dXyQvTkoiNVtsXAgFTXmL", "Bermondsey Bosom (Right)", "King Krule");
new Song("0Xcy81PsJCOO6mhLZaQyQ4", "Perfecto", "Mac Miller");
new Song("68QKxaWHcyxF5aEm4z1CVE", "Art Project", "Art Contest");
new Song("4tlqYj5LHUpXNBN1F0Iw5p", "Lo Que Construimos", "Natalia Lafourcade");
new Song("4XOlo2K3XX1ICy1KfEiWyO", "Solo", "Samsa");
new Song("64gyqTtDDel7B2NoEkOa0A", "Objects in the Mirror", "Mac Miller");
new Song("35xnCYrjXbuqhgl7E0rhck", "Stay Home", "American Football");
new Song("1B6CHcim4uHt8NIy1Bamqc", "In The Ground", "Illiterate Light");
new Song("2VhXTSo5qSsvoLWn0haQcv", "Mi Tierra Veracruzana", "Natalia Lafourcade");
new Song("5p7GiBZNL1afJJDUrOA6C8", "Hurt Feelings", "Mac Miller");
new Song("6VNjaZmWzm0aRXeBE1B5mM", "For Sure", "American Football");
new Song("7LYeytL8R2fuqnsW1s0k86", "Phone Call - From 'Eternal Sunshine of the Spotless Mind'/Score", "Jon Brion");
new Song("3wczwhLbWHPNXIL1fPd8qe", "María", "Cazamos Cometas");
new Song("2dgrYdgguVZKeCsrVb9XEs", "What's the Use?", "Mac Miller");
new Song("2ov7jzg8iAWWlpZuaXPUBK", "Dormir Sin Coger", "Arroba Nat");
new Song("1gTFwhHHsk4LwKGcLLe7r5", "Dmi Thing in Which New Information Is Introduced", "Jon Brion");
new Song("6IBpFG2LU2udYofIuROp3w", "Lost In The Light", "Bahamas");
new Song("0okvm6ZcKwucPFK0xhOjsM", "Arrúllame", "NORTE");
new Song("2TFWWixF1C3lwoT3P7g8hT", "For That Second", "Rob Scallon");
new Song("0304W5CLkIPtsw5UzK6Enr", "You Know I Should Be Leaving Soon", "American Football");
new Song("6OGOOLwgqrlVdwIuPbbz3r", "Pantera", "Jesse Baez");
new Song("0EA2RhRHL4KWeNa7JfD1Yw", "So It Goes", "Mac Miller");
new Song("26AYR77170U49cMcXB7aRV", "Feeling This", "blink-182");
new Song("5k8eNtmqlKe21qjIFIp1Du", "I. Flight of the Navigator", "Childish Gambino");
new Song("1GhiA5XvAywQNma9eK7XL4", "Friendship", "Big Big Love");
new Song("6l3A2EWZSOA8LTMmzRCyD3", "Dream House", "Deafheaven");
new Song("6V2QgOIMT94HhsfeIVbbZm", "Manila", "Maribou State");
new Song("1pKziOaiDCnrgMOqzQMtu2", "I'll See You When We're Both Not So Emotional", "American Football");
new Song("3YnwIp2b99p3e5dsFTXIIx", "Dunno", "Mac Miller");
new Song("3EAUSlUzVTLhxLn8Fhpz5V", "Irresistible", "Deafheaven");
new Song("6H5JsDwJDTmOBaq6E5T6SP", "Cute Thing", "Car Seat Headrest");
new Song("3UEpvJxIpzbR3w0oOa0zbB", "Intro", "Cazamos Cometas");
new Song("7pmW5pnmt4neelpBilTJHd", "This Old Machine", "Coconut Records");
new Song("0w2kfnU1PFKxjmZFQ1J1X8", "Overthinking", "Acid Ghost");
