class Album {
    constructor(uri, name, artist) {
        this.uri = uri;
        this.name = name;
        this.artist = artist;
        albums.push(this);
    }

    get_embeded() {
        return "https://open.spotify.com/embed/album/" + this.uri;
    }
}

new Album("27C6iNWoN1gmSHIpPGVgkS", "The Avalanche", "Owen");
new Album("6t0eIKq8adhPxIWP6TWhgP", "Seul", "Garou");
new Album("2t1JMhasqIbvoWb89rt2AV", "Lucio Dalla (Legacy Edition)", "Lucio Dalla");
new Album("12Biup1Sq5hpHsX85gJPb2", "Slide", "George Clanton");
new Album("60qph1sDjhgZtPR4IEnu5Y", "Grandma", "Unique Salonga");
new Album("4jgmGaLp4n8oFEoEQHR7A2", "11:11", "11:11");
new Album("7MtrCHFK57syVaitrSwSAY", "Silver Rose", "Silver Rose");
new Album("4E0m7AIVc2d2QZMrMNXdMZ", "Reflektor", "Arcade Fire");
new Album("6zmDdgPRKrvYwXk8eWv3iK", "6 Feet Beneath The Moon", "King Krule");
new Album("6UsJMFZbhzvWrTDX7vr3pr", "Almanueva", "The Guadaloops");
new Album("6Ulu31dfRTpIAud08ZIhXd", "The OOZ", "King Krule");
new Album("3dsjH0D0Co0X7oii3a7FO8", "Go Slow", "deca joins");
new Album("54xM746igJkdPJenRhW1za", "Days of Thunder", "The Midnight");
new Album("2vBa3poU0e82yfPtxcn9lg", "Joy as an Act of Resistance.", "IDLES");
new Album("7uwHUvVHDAEKxyXCoZYFIF", "Florence (Original Soundtrack)", "Kevin Penkin");
new Album("5yOO5ZvqDZx5Sr8jOGtWRR", "Eternal Sunshine Of The Spotless Mind", "Various Artists");
new Album("0LIWkw76T7O499slpRTeQ1", "Lady Bird (Original Motion Picture Soundtrack)", "Jon Brion");
new Album("6YKk4wlKdACRITGKmGnoIm", "Nectar", "Joji");
new Album("3g5x7FHBksAsL5syfukMwI", "Chronovision", "Oberhofer");
new Album("0MlfbX8SY5emphjwETJSRu", "D'arcy", "No Somos Marineros");
new Album("00uqjqwLruO346z3cNlNqG", "Cheap Queen", "King Princess");
new Album("2ibaIuHTpCYUUyXrFkBaQ7", "La Muerte De Zacarías", "Lara Project");
new Album("0EzyBlpS4V0EiXkoW4xtul", "Love & Decay", "Spotlights");
new Album("1tuoWW0TpoI5oacIjwYBdL", "Making a Door Less Open", "Car Seat Headrest");
new Album("0hMZay6SSlgGuS1IrxCVdo", "Era del Vacío", "Molinette Cinema");
new Album("0kAlEeID2MPd2JYT3Iwegp", "Delaware", "Drop Nineteens");
new Album("409ucdW5uJn96fKCsHWPDg", "My Mind Makes Noises", "Pale Waves");
new Album("1AVZ6ej2XcpHtlTqTy91qt", "Tiempos Raros", "El Shirota");
new Album("1tFsLlrFZVNpExRX3cg0WV", "Smells Like Quarantine Spirit (Live Session)", "Sunshine Pink");
new Album("162WY2ZAoenA3bCPZ0fXJH", "Dwell", "The Moving Pictures");
new Album("6iOCv7oGL5sGi2aVnRz2BI", "What Kinda Music", "Tom Misch");
new Album("0WzOtZBpXvWdNdH7hCJ4qo", "K.I.D.S.", "Mac Miller");
new Album("1roJDKHlQXToKPS4l9JI8H", "Todo Sentimiento Es Ya Memoria", "NORTE");
new Album("2qGq0iQFEjrcDprsd7QSFx", "They Want My Soul", "Spoon");
new Album("33szFJNdxgVGQa518rOohL", "La Dinastía Scorpio", "El Mató a un Policía Motorizado");
new Album("31WBtpvBAN0heOz3YUuVnI", "The Silhouette", "Cold Violets");
new Album("1JU4XTyTzADBQE1KpM0Wtx", "The Earth Is Not a Cold Dead Place", "Explosions In The Sky");
new Album("0jLf8ecN5HjstQqPAjJlsS", "California (Deluxe Edition)", "blink-182");
new Album("2NBVxjZcbH5H1N1Ab2ExDH", "Apricot Princess", "Rex Orange County");
new Album("600ClrWRsAr7jZ0qjaBLHz", "3.15.20", "Childish Gambino");
new Album("27ThgFMUAx3MXLQ297DzWF", "Hive Mind", "The Internet");
new Album("2O7cV8FLOPbOttvFVCU1bR", "Mariposa", "Felly");
new Album("4alcGHjstaALJHHiljfy3H", "DAMN. COLLECTORS EDITION.", "Kendrick Lamar");
new Album("51WLEfPEEkzAWurvuY6Gco", "Veteran", "JPEGMAFIA");
new Album("36lJLPoPPOKNFddTAcirnc", "In Rainbows (Disk 2)", "Radiohead");
new Album("7eyQXxuf2nGj9d2367Gi5f", "In Rainbows", "Radiohead");
new Album("5LsyqeWryTmxsmda4xkm5a", "UNLOCKED", "Denzel Curry");
new Album("19RUXBFyM4PpmrLRdtqWbp", "Kid A", "Radiohead");
new Album("0FZK97MXMm5mUQ8mtudjuK", "The Black Parade", "My Chemical Romance");
new Album("2epVE7UZnRSaCIJb0mjIPM", "Blue Scholars", "Blue Scholars");
new Album("7JbbUP152jaRbhQ7CJ1DOy", "Musas (Un Homenaje al Folclore Latinoamericano en Manos de Los Macorinos), Vol. 2", "Natalia Lafourcade");
new Album("4hBTxv4QRPePXCFcEI7Vjp", "blink-182", "blink-182");
new Album("0nmCwOAFeqD69X1MWwKTS6", "It Was Divine", "Alina Baraz");
new Album("6SWmGozzQDUaczHXMuE8Za", "Malibu Nights", "LANY");
new Album("2yAyZp16EbanQ9pBwQs70x", "A Different Age", "Current Joys");
new Album("3wUv2IjD5hPrqlPakpczQa", "I Don't Like Shit, I Don't Go Outside: An Album by Earl Sweatshirt", "Earl Sweatshirt");
new Album("5cW1jp3GGSe06JfZGPziW8", "Two Songs", "Art Contest");
new Album("30isRfL4u7fowKgTVsydDt", "Musas (Un Homenaje al Folclore Latinoamericano en Manos de Los Macorinos, Vol. 1)", "Natalia Lafourcade");
new Album("748dZDqSZy6aPXKcI9H80u", "good kid, m.A.A.d city (Deluxe)", "Kendrick Lamar");
new Album("4NgWzgASdbieyVnEBpyvcQ", "Conejo En El Sombrero", "La Gusana Ciega");
new Album("1ywMOLYln5Df2bF70jtydj", "Disco de Oro", "Little Jesus");
new Album("2Tyx5dLhHYkx6zeAdVaTzN", "GO:OD AM", "Mac Miller");
new Album("76cek8jEdNsxH60aUu8Qtj", "To Pimp A Butterfly", "Kendrick Lamar");
new Album("6Te111t5gDZ7W94myHRqUt", "CARE FOR ME", "Saba");
new Album("0S0KGZnfBGSIssfF54WSJh", "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?", "Billie Eilish");
new Album("1uoN9djowbSSttHLe2Nfwn", "Toothpick", "Kai Straw");
new Album("4TkmrrpjlPoCPpGyDN3rkF", "A Deeper Understanding", "The War On Drugs");
new Album("2A4sin52eEjkavgFwPdEoZ", "Sound & Color", "Alabama Shakes");
new Album("33ZqJmmqFE8Z7Ak1Lxbnfb", "The 1975", "The 1975");
new Album("2iA7rzpQsOfAPkfH4Ekp7f", "Ordinary Corrupt Human Love", "Deafheaven");
new Album("7MLDnEVUacleMDICnnAWuF", "Man Alive!", "King Krule");
new Album("5ilsl5R2lGACTnPZMKIp7o", "All My Heroes Are Cornballs", "JPEGMAFIA");
new Album("5YCFp2g2ZZUc0bKNAWyYHN", "La Sintesis O'Konor", "El Mató a un Policía Motorizado");
new Album("2X4swA3UkpqAS8bbXYgP9k", "Destellos", "CLUBZ");
new Album("5u8hliZZtH3mc6o7BJRmVP", "Dead Cities, Red Seas & Lost Ghosts", "M83");
new Album("7JX33G6W9Zi9ViEvUumX8E", "Norte (Japanese Version)", "Little Jesus");
new Album("1ny9ec75rSo3SOg1EiDRRW", "Panoramas", "Klaatu Suuns");
new Album("2kKXGWaCEl06EKZ4DxBJIT", "Sunbather", "Deafheaven");
new Album("4VFG1DOuTeDMBjBLZT7hCK", "Malibu", "Anderson .Paak");
new Album("6V9YnBmFjWmXCBaUVRCVXP", "Amnesiac", "Radiohead");
new Album("6vuykQgDLUCiZ7YggIpLM9", "A Moon Shaped Pool", "Radiohead");
new Album("6PWXKiakqhI17mTYM4y6oY", "A Brief Inquiry Into Online Relationships", "The 1975");
new Album("01FCoGEQ3NFWF4fHJzdiax", "Madvillainy", "Madvillain");
new Album("26DseQO366JfXwIP7dIgQj", "Teens of Denial", "Car Seat Headrest");
new Album("2xkZV2Hl1Omi8rk2D7t5lN", "The New Abnormal", "The Strokes");
new Album("6yDcHjoEqNkkl9UC6KSlFE", "Un Canto por México, Vol. 1", "Natalia Lafourcade");
new Album("1TobaDcf1kuip5YpaM8crC", "7", "7");
new Album("1E5maXoUUIcaDEETyDpi3V", "Nitro", "Jesse Baez");
new Album("7fFUZ9J5aTu18MYcBiPOny", "Go Slow", "deca joins");
new Album("44e9RWIVc5NCKmqNfLEHgI", "Homesick", "Sadfields");
new Album("5ooYAFLqUJiXfGzjVgG5N0", "Río Salvaje", "Little Jesus");
new Album("101nIHm9fdR1wLMgjiLmhT", "Illiterate Light", "Illiterate Light");
new Album("4Carzsnpd6yvuHZ49I0oz8", "'Awaken, My Love!'", "Childish Gambino");
new Album("7xV2TzoaVc0ycW7fwBwAml", "Fine Line", "Harry Styles");
new Album("3wRBlpk5PRoixwOnLujTal", "American Football", "American Football");
new Album("3PRMdCzUdj3LmnyLVU1cLr", "Friendship", "Big Big Love");
new Album("3XIKKZu6j73mu2MKFdi9JX", "María", "Cazamos Cometas");
new Album("1rBDUTycaO0IFrCGlz3l32", "Beacon", "Matt Duncan");
new Album("5zi7WsKlIiUXv09tbGLKsE", "IGOR", "Tyler, The Creator");
new Album("1JFmNyVPdBF1ECvv4fhpW4", "I like it when you sleep, for you are so beautiful yet so unaware of it", "The 1975");
new Album("3T02fCxAjApu18taJLLbyN", "Watching Movies with the Sound Off (Deluxe Edition)", "Mac Miller");
new Album("6f6tko6NWoH00cyFOl4VYQ", "The Divine Feminine", "Mac Miller");
new Album("5wtE5aLX5r7jOosmPhJhhk", "Swimming", "Mac Miller");
new Album("1YZ3k65Mqw3G8FzYlW1mmp", "Circles (Deluxe)", "Mac Miller");
new Album("6EB14IXV5oyOiItGBv7mtG", "Hurry up, We're Dreaming", "M83");
new Album("7viNUmZZ8ztn2UB4XB3jIL", "2014 Forest Hills Drive", "J. Cole");
new Album("3CCnGldVQ90c26aFATC1PW", "4 Your Eyez Only", "J. Cole");
new Album("3mH6qwIy9crq0I9YQbOuDf", "Blonde", "Frank Ocean");
new Album("4GNIhgEGXzWGAefgN5qjdU", "Because the Internet", "Childish Gambino");
new Album("20U1UWeGcGq7JVW0tf8yfH", "Twin Fantasy", "Car Seat Headrest");
